/*
Polaris Management Service

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package polarismgmt

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "github.com/tower/polaris-management-go"
)

func Test_polarismgmt_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService AddGrantToCatalogRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string
		var catalogRoleName string

		httpRes, err := apiClient.DefaultAPI.AddGrantToCatalogRole(context.Background(), catalogName, catalogRoleName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService AssignCatalogRoleToPrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalRoleName string
		var catalogName string

		httpRes, err := apiClient.DefaultAPI.AssignCatalogRoleToPrincipalRole(context.Background(), principalRoleName, catalogName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService AssignPrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalName string

		httpRes, err := apiClient.DefaultAPI.AssignPrincipalRole(context.Background(), principalName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService CreateCatalog", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.CreateCatalog(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService CreateCatalogRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string

		resp, httpRes, err := apiClient.DefaultAPI.CreateCatalogRole(context.Background(), catalogName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService CreatePrincipal", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.CreatePrincipal(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService CreatePrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.CreatePrincipalRole(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeleteCatalog", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string

		httpRes, err := apiClient.DefaultAPI.DeleteCatalog(context.Background(), catalogName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeleteCatalogRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string
		var catalogRoleName string

		httpRes, err := apiClient.DefaultAPI.DeleteCatalogRole(context.Background(), catalogName, catalogRoleName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeletePrincipal", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalName string

		httpRes, err := apiClient.DefaultAPI.DeletePrincipal(context.Background(), principalName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeletePrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalRoleName string

		httpRes, err := apiClient.DefaultAPI.DeletePrincipalRole(context.Background(), principalRoleName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetCatalog", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string

		resp, httpRes, err := apiClient.DefaultAPI.GetCatalog(context.Background(), catalogName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetCatalogRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string
		var catalogRoleName string

		resp, httpRes, err := apiClient.DefaultAPI.GetCatalogRole(context.Background(), catalogName, catalogRoleName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetPrincipal", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalName string

		resp, httpRes, err := apiClient.DefaultAPI.GetPrincipal(context.Background(), principalName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetPrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalRoleName string

		resp, httpRes, err := apiClient.DefaultAPI.GetPrincipalRole(context.Background(), principalRoleName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListAssigneePrincipalRolesForCatalogRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string
		var catalogRoleName string

		resp, httpRes, err := apiClient.DefaultAPI.ListAssigneePrincipalRolesForCatalogRole(context.Background(), catalogName, catalogRoleName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListAssigneePrincipalsForPrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalRoleName string

		resp, httpRes, err := apiClient.DefaultAPI.ListAssigneePrincipalsForPrincipalRole(context.Background(), principalRoleName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListCatalogRoles", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string

		resp, httpRes, err := apiClient.DefaultAPI.ListCatalogRoles(context.Background(), catalogName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListCatalogRolesForPrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalRoleName string
		var catalogName string

		resp, httpRes, err := apiClient.DefaultAPI.ListCatalogRolesForPrincipalRole(context.Background(), principalRoleName, catalogName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListCatalogs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.ListCatalogs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListGrantsForCatalogRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string
		var catalogRoleName string

		resp, httpRes, err := apiClient.DefaultAPI.ListGrantsForCatalogRole(context.Background(), catalogName, catalogRoleName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListPrincipalRoles", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.ListPrincipalRoles(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListPrincipalRolesAssigned", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalName string

		resp, httpRes, err := apiClient.DefaultAPI.ListPrincipalRolesAssigned(context.Background(), principalName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ListPrincipals", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.ListPrincipals(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ResetCredentials", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalName string

		resp, httpRes, err := apiClient.DefaultAPI.ResetCredentials(context.Background(), principalName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService RevokeCatalogRoleFromPrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalRoleName string
		var catalogName string
		var catalogRoleName string

		httpRes, err := apiClient.DefaultAPI.RevokeCatalogRoleFromPrincipalRole(context.Background(), principalRoleName, catalogName, catalogRoleName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService RevokeGrantFromCatalogRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string
		var catalogRoleName string

		httpRes, err := apiClient.DefaultAPI.RevokeGrantFromCatalogRole(context.Background(), catalogName, catalogRoleName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService RevokePrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalName string
		var principalRoleName string

		httpRes, err := apiClient.DefaultAPI.RevokePrincipalRole(context.Background(), principalName, principalRoleName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService RotateCredentials", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalName string

		resp, httpRes, err := apiClient.DefaultAPI.RotateCredentials(context.Background(), principalName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UpdateCatalog", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string

		resp, httpRes, err := apiClient.DefaultAPI.UpdateCatalog(context.Background(), catalogName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UpdateCatalogRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var catalogName string
		var catalogRoleName string

		resp, httpRes, err := apiClient.DefaultAPI.UpdateCatalogRole(context.Background(), catalogName, catalogRoleName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UpdatePrincipal", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalName string

		resp, httpRes, err := apiClient.DefaultAPI.UpdatePrincipal(context.Background(), principalName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UpdatePrincipalRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var principalRoleName string

		resp, httpRes, err := apiClient.DefaultAPI.UpdatePrincipalRole(context.Background(), principalRoleName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
