/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// ViewPrivilege the model 'ViewPrivilege'
type ViewPrivilege string

// List of ViewPrivilege
const (
	VIEWPRIVILEGE_CATALOG_MANAGE_ACCESS ViewPrivilege = "CATALOG_MANAGE_ACCESS"
	VIEWPRIVILEGE_VIEW_DROP ViewPrivilege = "VIEW_DROP"
	VIEWPRIVILEGE_VIEW_LIST ViewPrivilege = "VIEW_LIST"
	VIEWPRIVILEGE_VIEW_READ_PROPERTIES ViewPrivilege = "VIEW_READ_PROPERTIES"
	VIEWPRIVILEGE_VIEW_WRITE_PROPERTIES ViewPrivilege = "VIEW_WRITE_PROPERTIES"
	VIEWPRIVILEGE_VIEW_FULL_METADATA ViewPrivilege = "VIEW_FULL_METADATA"
)

// All allowed values of ViewPrivilege enum
var AllowedViewPrivilegeEnumValues = []ViewPrivilege{
	"CATALOG_MANAGE_ACCESS",
	"VIEW_DROP",
	"VIEW_LIST",
	"VIEW_READ_PROPERTIES",
	"VIEW_WRITE_PROPERTIES",
	"VIEW_FULL_METADATA",
}

func (v *ViewPrivilege) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ViewPrivilege(value)
	for _, existing := range AllowedViewPrivilegeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ViewPrivilege", value)
}

// NewViewPrivilegeFromValue returns a pointer to a valid ViewPrivilege
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewViewPrivilegeFromValue(v string) (*ViewPrivilege, error) {
	ev := ViewPrivilege(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ViewPrivilege: valid values are %v", v, AllowedViewPrivilegeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ViewPrivilege) IsValid() bool {
	for _, existing := range AllowedViewPrivilegeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ViewPrivilege value
func (v ViewPrivilege) Ptr() *ViewPrivilege {
	return &v
}

type NullableViewPrivilege struct {
	value *ViewPrivilege
	isSet bool
}

func (v NullableViewPrivilege) Get() *ViewPrivilege {
	return v.value
}

func (v *NullableViewPrivilege) Set(val *ViewPrivilege) {
	v.value = val
	v.isSet = true
}

func (v NullableViewPrivilege) IsSet() bool {
	return v.isSet
}

func (v *NullableViewPrivilege) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewPrivilege(val *ViewPrivilege) *NullableViewPrivilege {
	return &NullableViewPrivilege{value: val, isSet: true}
}

func (v NullableViewPrivilege) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewPrivilege) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

