/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the HadoopConnectionConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HadoopConnectionConfigInfo{}

// HadoopConnectionConfigInfo struct for HadoopConnectionConfigInfo
type HadoopConnectionConfigInfo struct {
	ConnectionConfigInfo
	// The file path to where this catalog should store tables
	Warehouse *string `json:"warehouse,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HadoopConnectionConfigInfo HadoopConnectionConfigInfo

// NewHadoopConnectionConfigInfo instantiates a new HadoopConnectionConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHadoopConnectionConfigInfo(connectionType string) *HadoopConnectionConfigInfo {
	this := HadoopConnectionConfigInfo{}
	this.ConnectionType = connectionType
	return &this
}

// NewHadoopConnectionConfigInfoWithDefaults instantiates a new HadoopConnectionConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHadoopConnectionConfigInfoWithDefaults() *HadoopConnectionConfigInfo {
	this := HadoopConnectionConfigInfo{}
	return &this
}

// GetWarehouse returns the Warehouse field value if set, zero value otherwise.
func (o *HadoopConnectionConfigInfo) GetWarehouse() string {
	if o == nil || IsNil(o.Warehouse) {
		var ret string
		return ret
	}
	return *o.Warehouse
}

// GetWarehouseOk returns a tuple with the Warehouse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HadoopConnectionConfigInfo) GetWarehouseOk() (*string, bool) {
	if o == nil || IsNil(o.Warehouse) {
		return nil, false
	}
	return o.Warehouse, true
}

// HasWarehouse returns a boolean if a field has been set.
func (o *HadoopConnectionConfigInfo) HasWarehouse() bool {
	if o != nil && !IsNil(o.Warehouse) {
		return true
	}

	return false
}

// SetWarehouse gets a reference to the given string and assigns it to the Warehouse field.
func (o *HadoopConnectionConfigInfo) SetWarehouse(v string) {
	o.Warehouse = &v
}

func (o HadoopConnectionConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HadoopConnectionConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Warehouse) {
		toSerialize["warehouse"] = o.Warehouse
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HadoopConnectionConfigInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectionType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHadoopConnectionConfigInfo := _HadoopConnectionConfigInfo{}

	err = json.Unmarshal(data, &varHadoopConnectionConfigInfo)

	if err != nil {
		return err
	}

	*o = HadoopConnectionConfigInfo(varHadoopConnectionConfigInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "warehouse")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHadoopConnectionConfigInfo struct {
	value *HadoopConnectionConfigInfo
	isSet bool
}

func (v NullableHadoopConnectionConfigInfo) Get() *HadoopConnectionConfigInfo {
	return v.value
}

func (v *NullableHadoopConnectionConfigInfo) Set(val *HadoopConnectionConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableHadoopConnectionConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableHadoopConnectionConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHadoopConnectionConfigInfo(val *HadoopConnectionConfigInfo) *NullableHadoopConnectionConfigInfo {
	return &NullableHadoopConnectionConfigInfo{value: val, isSet: true}
}

func (v NullableHadoopConnectionConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHadoopConnectionConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


