/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the AwsStorageConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsStorageConfigInfo{}

// AwsStorageConfigInfo aws storage configuration info
type AwsStorageConfigInfo struct {
	StorageConfigInfo
	// the aws role arn that grants privileges on the S3 buckets
	RoleArn *string `json:"roleArn,omitempty"`
	// an optional external id used to establish a trust relationship with AWS in the trust policy
	ExternalId *string `json:"externalId,omitempty"`
	// the aws user arn used to assume the aws role
	UserArn *string `json:"userArn,omitempty"`
	// the aws region where data is stored
	Region *string `json:"region,omitempty"`
	// endpoint for S3 requests (optional). Clients always see this value (if it is set). Polaris Servers may be configured to use a different endpoint URI via the `endpointInternal` property.
	Endpoint *string `json:"endpoint,omitempty"`
	// endpoint for STS requests made by the Polaris Server (optional). If not set, defaults to 'endpointInternal' (which in turn defaults to `endpoint`).
	StsEndpoint *string `json:"stsEndpoint,omitempty"`
	// if set to `true`, instructs Polaris Servers to avoid using the STS endpoints when obtaining credentials for accessing data and metadata files within the related catalog. Setting this property to `true` effectively disables vending storage credentials to clients. This setting is intended for configuring catalogs with S3-compatible storage implementations that do not support STS.
	StsUnavailable *bool `json:"stsUnavailable,omitempty"`
	// endpoint for S3 requests made by the Polaris Server (optional). If set, Polaris Service will use this value instead of `endpoint`. If not set, defaults to `endpoint`. Iceberg REST API clients never see this value.
	EndpointInternal *string `json:"endpointInternal,omitempty"`
	// Whether S3 requests to files in this catalog should use 'path-style addressing for buckets'.
	PathStyleAccess *bool `json:"pathStyleAccess,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AwsStorageConfigInfo AwsStorageConfigInfo

// NewAwsStorageConfigInfo instantiates a new AwsStorageConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsStorageConfigInfo(storageType string) *AwsStorageConfigInfo {
	this := AwsStorageConfigInfo{}
	this.StorageType = storageType
	var pathStyleAccess bool = false
	this.PathStyleAccess = &pathStyleAccess
	return &this
}

// NewAwsStorageConfigInfoWithDefaults instantiates a new AwsStorageConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsStorageConfigInfoWithDefaults() *AwsStorageConfigInfo {
	this := AwsStorageConfigInfo{}
	var pathStyleAccess bool = false
	this.PathStyleAccess = &pathStyleAccess
	return &this
}

// GetRoleArn returns the RoleArn field value if set, zero value otherwise.
func (o *AwsStorageConfigInfo) GetRoleArn() string {
	if o == nil || IsNil(o.RoleArn) {
		var ret string
		return ret
	}
	return *o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsStorageConfigInfo) GetRoleArnOk() (*string, bool) {
	if o == nil || IsNil(o.RoleArn) {
		return nil, false
	}
	return o.RoleArn, true
}

// HasRoleArn returns a boolean if a field has been set.
func (o *AwsStorageConfigInfo) HasRoleArn() bool {
	if o != nil && !IsNil(o.RoleArn) {
		return true
	}

	return false
}

// SetRoleArn gets a reference to the given string and assigns it to the RoleArn field.
func (o *AwsStorageConfigInfo) SetRoleArn(v string) {
	o.RoleArn = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *AwsStorageConfigInfo) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsStorageConfigInfo) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *AwsStorageConfigInfo) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *AwsStorageConfigInfo) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetUserArn returns the UserArn field value if set, zero value otherwise.
func (o *AwsStorageConfigInfo) GetUserArn() string {
	if o == nil || IsNil(o.UserArn) {
		var ret string
		return ret
	}
	return *o.UserArn
}

// GetUserArnOk returns a tuple with the UserArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsStorageConfigInfo) GetUserArnOk() (*string, bool) {
	if o == nil || IsNil(o.UserArn) {
		return nil, false
	}
	return o.UserArn, true
}

// HasUserArn returns a boolean if a field has been set.
func (o *AwsStorageConfigInfo) HasUserArn() bool {
	if o != nil && !IsNil(o.UserArn) {
		return true
	}

	return false
}

// SetUserArn gets a reference to the given string and assigns it to the UserArn field.
func (o *AwsStorageConfigInfo) SetUserArn(v string) {
	o.UserArn = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *AwsStorageConfigInfo) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsStorageConfigInfo) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *AwsStorageConfigInfo) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *AwsStorageConfigInfo) SetRegion(v string) {
	o.Region = &v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *AwsStorageConfigInfo) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsStorageConfigInfo) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *AwsStorageConfigInfo) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *AwsStorageConfigInfo) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetStsEndpoint returns the StsEndpoint field value if set, zero value otherwise.
func (o *AwsStorageConfigInfo) GetStsEndpoint() string {
	if o == nil || IsNil(o.StsEndpoint) {
		var ret string
		return ret
	}
	return *o.StsEndpoint
}

// GetStsEndpointOk returns a tuple with the StsEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsStorageConfigInfo) GetStsEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.StsEndpoint) {
		return nil, false
	}
	return o.StsEndpoint, true
}

// HasStsEndpoint returns a boolean if a field has been set.
func (o *AwsStorageConfigInfo) HasStsEndpoint() bool {
	if o != nil && !IsNil(o.StsEndpoint) {
		return true
	}

	return false
}

// SetStsEndpoint gets a reference to the given string and assigns it to the StsEndpoint field.
func (o *AwsStorageConfigInfo) SetStsEndpoint(v string) {
	o.StsEndpoint = &v
}

// GetStsUnavailable returns the StsUnavailable field value if set, zero value otherwise.
func (o *AwsStorageConfigInfo) GetStsUnavailable() bool {
	if o == nil || IsNil(o.StsUnavailable) {
		var ret bool
		return ret
	}
	return *o.StsUnavailable
}

// GetStsUnavailableOk returns a tuple with the StsUnavailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsStorageConfigInfo) GetStsUnavailableOk() (*bool, bool) {
	if o == nil || IsNil(o.StsUnavailable) {
		return nil, false
	}
	return o.StsUnavailable, true
}

// HasStsUnavailable returns a boolean if a field has been set.
func (o *AwsStorageConfigInfo) HasStsUnavailable() bool {
	if o != nil && !IsNil(o.StsUnavailable) {
		return true
	}

	return false
}

// SetStsUnavailable gets a reference to the given bool and assigns it to the StsUnavailable field.
func (o *AwsStorageConfigInfo) SetStsUnavailable(v bool) {
	o.StsUnavailable = &v
}

// GetEndpointInternal returns the EndpointInternal field value if set, zero value otherwise.
func (o *AwsStorageConfigInfo) GetEndpointInternal() string {
	if o == nil || IsNil(o.EndpointInternal) {
		var ret string
		return ret
	}
	return *o.EndpointInternal
}

// GetEndpointInternalOk returns a tuple with the EndpointInternal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsStorageConfigInfo) GetEndpointInternalOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointInternal) {
		return nil, false
	}
	return o.EndpointInternal, true
}

// HasEndpointInternal returns a boolean if a field has been set.
func (o *AwsStorageConfigInfo) HasEndpointInternal() bool {
	if o != nil && !IsNil(o.EndpointInternal) {
		return true
	}

	return false
}

// SetEndpointInternal gets a reference to the given string and assigns it to the EndpointInternal field.
func (o *AwsStorageConfigInfo) SetEndpointInternal(v string) {
	o.EndpointInternal = &v
}

// GetPathStyleAccess returns the PathStyleAccess field value if set, zero value otherwise.
func (o *AwsStorageConfigInfo) GetPathStyleAccess() bool {
	if o == nil || IsNil(o.PathStyleAccess) {
		var ret bool
		return ret
	}
	return *o.PathStyleAccess
}

// GetPathStyleAccessOk returns a tuple with the PathStyleAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsStorageConfigInfo) GetPathStyleAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.PathStyleAccess) {
		return nil, false
	}
	return o.PathStyleAccess, true
}

// HasPathStyleAccess returns a boolean if a field has been set.
func (o *AwsStorageConfigInfo) HasPathStyleAccess() bool {
	if o != nil && !IsNil(o.PathStyleAccess) {
		return true
	}

	return false
}

// SetPathStyleAccess gets a reference to the given bool and assigns it to the PathStyleAccess field.
func (o *AwsStorageConfigInfo) SetPathStyleAccess(v bool) {
	o.PathStyleAccess = &v
}

func (o AwsStorageConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsStorageConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RoleArn) {
		toSerialize["roleArn"] = o.RoleArn
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if !IsNil(o.UserArn) {
		toSerialize["userArn"] = o.UserArn
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.StsEndpoint) {
		toSerialize["stsEndpoint"] = o.StsEndpoint
	}
	if !IsNil(o.StsUnavailable) {
		toSerialize["stsUnavailable"] = o.StsUnavailable
	}
	if !IsNil(o.EndpointInternal) {
		toSerialize["endpointInternal"] = o.EndpointInternal
	}
	if !IsNil(o.PathStyleAccess) {
		toSerialize["pathStyleAccess"] = o.PathStyleAccess
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AwsStorageConfigInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"storageType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAwsStorageConfigInfo := _AwsStorageConfigInfo{}

	err = json.Unmarshal(data, &varAwsStorageConfigInfo)

	if err != nil {
		return err
	}

	*o = AwsStorageConfigInfo(varAwsStorageConfigInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "roleArn")
		delete(additionalProperties, "externalId")
		delete(additionalProperties, "userArn")
		delete(additionalProperties, "region")
		delete(additionalProperties, "endpoint")
		delete(additionalProperties, "stsEndpoint")
		delete(additionalProperties, "stsUnavailable")
		delete(additionalProperties, "endpointInternal")
		delete(additionalProperties, "pathStyleAccess")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAwsStorageConfigInfo struct {
	value *AwsStorageConfigInfo
	isSet bool
}

func (v NullableAwsStorageConfigInfo) Get() *AwsStorageConfigInfo {
	return v.value
}

func (v *NullableAwsStorageConfigInfo) Set(val *AwsStorageConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsStorageConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsStorageConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsStorageConfigInfo(val *AwsStorageConfigInfo) *NullableAwsStorageConfigInfo {
	return &NullableAwsStorageConfigInfo{value: val, isSet: true}
}

func (v NullableAwsStorageConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsStorageConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


