/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the ConnectionConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionConfigInfo{}

// ConnectionConfigInfo A connection configuration representing a remote catalog service. IMPORTANT - Specifying a ConnectionConfigInfo in an ExternalCatalog is currently an experimental API and is subject to change.
type ConnectionConfigInfo struct {
	// The type of remote catalog service represented by this connection
	ConnectionType string `json:"connectionType"`
	// URI to the remote catalog service
	Uri *string `json:"uri,omitempty"`
	AuthenticationParameters *AuthenticationParameters `json:"authenticationParameters,omitempty"`
	ServiceIdentity *ServiceIdentityInfo `json:"serviceIdentity,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectionConfigInfo ConnectionConfigInfo

// NewConnectionConfigInfo instantiates a new ConnectionConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionConfigInfo(connectionType string) *ConnectionConfigInfo {
	this := ConnectionConfigInfo{}
	this.ConnectionType = connectionType
	return &this
}

// NewConnectionConfigInfoWithDefaults instantiates a new ConnectionConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionConfigInfoWithDefaults() *ConnectionConfigInfo {
	this := ConnectionConfigInfo{}
	return &this
}

// GetConnectionType returns the ConnectionType field value
func (o *ConnectionConfigInfo) GetConnectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value
// and a boolean to check if the value has been set.
func (o *ConnectionConfigInfo) GetConnectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionType, true
}

// SetConnectionType sets field value
func (o *ConnectionConfigInfo) SetConnectionType(v string) {
	o.ConnectionType = v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *ConnectionConfigInfo) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionConfigInfo) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *ConnectionConfigInfo) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *ConnectionConfigInfo) SetUri(v string) {
	o.Uri = &v
}

// GetAuthenticationParameters returns the AuthenticationParameters field value if set, zero value otherwise.
func (o *ConnectionConfigInfo) GetAuthenticationParameters() AuthenticationParameters {
	if o == nil || IsNil(o.AuthenticationParameters) {
		var ret AuthenticationParameters
		return ret
	}
	return *o.AuthenticationParameters
}

// GetAuthenticationParametersOk returns a tuple with the AuthenticationParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionConfigInfo) GetAuthenticationParametersOk() (*AuthenticationParameters, bool) {
	if o == nil || IsNil(o.AuthenticationParameters) {
		return nil, false
	}
	return o.AuthenticationParameters, true
}

// HasAuthenticationParameters returns a boolean if a field has been set.
func (o *ConnectionConfigInfo) HasAuthenticationParameters() bool {
	if o != nil && !IsNil(o.AuthenticationParameters) {
		return true
	}

	return false
}

// SetAuthenticationParameters gets a reference to the given AuthenticationParameters and assigns it to the AuthenticationParameters field.
func (o *ConnectionConfigInfo) SetAuthenticationParameters(v AuthenticationParameters) {
	o.AuthenticationParameters = &v
}

// GetServiceIdentity returns the ServiceIdentity field value if set, zero value otherwise.
func (o *ConnectionConfigInfo) GetServiceIdentity() ServiceIdentityInfo {
	if o == nil || IsNil(o.ServiceIdentity) {
		var ret ServiceIdentityInfo
		return ret
	}
	return *o.ServiceIdentity
}

// GetServiceIdentityOk returns a tuple with the ServiceIdentity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionConfigInfo) GetServiceIdentityOk() (*ServiceIdentityInfo, bool) {
	if o == nil || IsNil(o.ServiceIdentity) {
		return nil, false
	}
	return o.ServiceIdentity, true
}

// HasServiceIdentity returns a boolean if a field has been set.
func (o *ConnectionConfigInfo) HasServiceIdentity() bool {
	if o != nil && !IsNil(o.ServiceIdentity) {
		return true
	}

	return false
}

// SetServiceIdentity gets a reference to the given ServiceIdentityInfo and assigns it to the ServiceIdentity field.
func (o *ConnectionConfigInfo) SetServiceIdentity(v ServiceIdentityInfo) {
	o.ServiceIdentity = &v
}

func (o ConnectionConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connectionType"] = o.ConnectionType
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	if !IsNil(o.AuthenticationParameters) {
		toSerialize["authenticationParameters"] = o.AuthenticationParameters
	}
	if !IsNil(o.ServiceIdentity) {
		toSerialize["serviceIdentity"] = o.ServiceIdentity
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectionConfigInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectionType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectionConfigInfo := _ConnectionConfigInfo{}

	err = json.Unmarshal(data, &varConnectionConfigInfo)

	if err != nil {
		return err
	}

	*o = ConnectionConfigInfo(varConnectionConfigInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "connectionType")
		delete(additionalProperties, "uri")
		delete(additionalProperties, "authenticationParameters")
		delete(additionalProperties, "serviceIdentity")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectionConfigInfo struct {
	value *ConnectionConfigInfo
	isSet bool
}

func (v NullableConnectionConfigInfo) Get() *ConnectionConfigInfo {
	return v.value
}

func (v *NullableConnectionConfigInfo) Set(val *ConnectionConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionConfigInfo(val *ConnectionConfigInfo) *NullableConnectionConfigInfo {
	return &NullableConnectionConfigInfo{value: val, isSet: true}
}

func (v NullableConnectionConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


