/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the GrantResources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantResources{}

// GrantResources struct for GrantResources
type GrantResources struct {
	Grants []GrantResource `json:"grants"`
	AdditionalProperties map[string]interface{}
}

type _GrantResources GrantResources

// NewGrantResources instantiates a new GrantResources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantResources(grants []GrantResource) *GrantResources {
	this := GrantResources{}
	this.Grants = grants
	return &this
}

// NewGrantResourcesWithDefaults instantiates a new GrantResources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantResourcesWithDefaults() *GrantResources {
	this := GrantResources{}
	return &this
}

// GetGrants returns the Grants field value
func (o *GrantResources) GetGrants() []GrantResource {
	if o == nil {
		var ret []GrantResource
		return ret
	}

	return o.Grants
}

// GetGrantsOk returns a tuple with the Grants field value
// and a boolean to check if the value has been set.
func (o *GrantResources) GetGrantsOk() ([]GrantResource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Grants, true
}

// SetGrants sets field value
func (o *GrantResources) SetGrants(v []GrantResource) {
	o.Grants = v
}

func (o GrantResources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantResources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["grants"] = o.Grants

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GrantResources) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"grants",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGrantResources := _GrantResources{}

	err = json.Unmarshal(data, &varGrantResources)

	if err != nil {
		return err
	}

	*o = GrantResources(varGrantResources)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "grants")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGrantResources struct {
	value *GrantResources
	isSet bool
}

func (v NullableGrantResources) Get() *GrantResources {
	return v.value
}

func (v *NullableGrantResources) Set(val *GrantResources) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantResources) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantResources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantResources(val *GrantResources) *NullableGrantResources {
	return &NullableGrantResources{value: val, isSet: true}
}

func (v NullableGrantResources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantResources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


