/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the ExternalCatalog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalCatalog{}

// ExternalCatalog An externally managed catalog
type ExternalCatalog struct {
	Catalog
	ConnectionConfigInfo *ConnectionConfigInfo `json:"connectionConfigInfo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ExternalCatalog ExternalCatalog

// NewExternalCatalog instantiates a new ExternalCatalog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalCatalog(type_ string, name string, properties CatalogProperties, storageConfigInfo StorageConfigInfo) *ExternalCatalog {
	this := ExternalCatalog{}
	this.Type = type_
	this.Name = name
	this.Properties = properties
	this.StorageConfigInfo = storageConfigInfo
	return &this
}

// NewExternalCatalogWithDefaults instantiates a new ExternalCatalog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalCatalogWithDefaults() *ExternalCatalog {
	this := ExternalCatalog{}
	return &this
}

// GetConnectionConfigInfo returns the ConnectionConfigInfo field value if set, zero value otherwise.
func (o *ExternalCatalog) GetConnectionConfigInfo() ConnectionConfigInfo {
	if o == nil || IsNil(o.ConnectionConfigInfo) {
		var ret ConnectionConfigInfo
		return ret
	}
	return *o.ConnectionConfigInfo
}

// GetConnectionConfigInfoOk returns a tuple with the ConnectionConfigInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalCatalog) GetConnectionConfigInfoOk() (*ConnectionConfigInfo, bool) {
	if o == nil || IsNil(o.ConnectionConfigInfo) {
		return nil, false
	}
	return o.ConnectionConfigInfo, true
}

// HasConnectionConfigInfo returns a boolean if a field has been set.
func (o *ExternalCatalog) HasConnectionConfigInfo() bool {
	if o != nil && !IsNil(o.ConnectionConfigInfo) {
		return true
	}

	return false
}

// SetConnectionConfigInfo gets a reference to the given ConnectionConfigInfo and assigns it to the ConnectionConfigInfo field.
func (o *ExternalCatalog) SetConnectionConfigInfo(v ConnectionConfigInfo) {
	o.ConnectionConfigInfo = &v
}

func (o ExternalCatalog) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalCatalog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConnectionConfigInfo) {
		toSerialize["connectionConfigInfo"] = o.ConnectionConfigInfo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExternalCatalog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"properties",
		"storageConfigInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExternalCatalog := _ExternalCatalog{}

	err = json.Unmarshal(data, &varExternalCatalog)

	if err != nil {
		return err
	}

	*o = ExternalCatalog(varExternalCatalog)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "connectionConfigInfo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExternalCatalog struct {
	value *ExternalCatalog
	isSet bool
}

func (v NullableExternalCatalog) Get() *ExternalCatalog {
	return v.value
}

func (v *NullableExternalCatalog) Set(val *ExternalCatalog) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalCatalog) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalCatalog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalCatalog(val *ExternalCatalog) *NullableExternalCatalog {
	return &NullableExternalCatalog{value: val, isSet: true}
}

func (v NullableExternalCatalog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalCatalog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
