/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// TablePrivilege the model 'TablePrivilege'
type TablePrivilege string

// List of TablePrivilege
const (
	TABLEPRIVILEGE_CATALOG_MANAGE_ACCESS TablePrivilege = "CATALOG_MANAGE_ACCESS"
	TABLEPRIVILEGE_TABLE_DROP TablePrivilege = "TABLE_DROP"
	TABLEPRIVILEGE_TABLE_LIST TablePrivilege = "TABLE_LIST"
	TABLEPRIVILEGE_TABLE_READ_PROPERTIES TablePrivilege = "TABLE_READ_PROPERTIES"
	TABLEPRIVILEGE_TABLE_WRITE_PROPERTIES TablePrivilege = "TABLE_WRITE_PROPERTIES"
	TABLEPRIVILEGE_TABLE_READ_DATA TablePrivilege = "TABLE_READ_DATA"
	TABLEPRIVILEGE_TABLE_WRITE_DATA TablePrivilege = "TABLE_WRITE_DATA"
	TABLEPRIVILEGE_TABLE_FULL_METADATA TablePrivilege = "TABLE_FULL_METADATA"
	TABLEPRIVILEGE_TABLE_ATTACH_POLICY TablePrivilege = "TABLE_ATTACH_POLICY"
	TABLEPRIVILEGE_TABLE_DETACH_POLICY TablePrivilege = "TABLE_DETACH_POLICY"
	TABLEPRIVILEGE_TABLE_ASSIGN_UUID TablePrivilege = "TABLE_ASSIGN_UUID"
	TABLEPRIVILEGE_TABLE_UPGRADE_FORMAT_VERSION TablePrivilege = "TABLE_UPGRADE_FORMAT_VERSION"
	TABLEPRIVILEGE_TABLE_ADD_SCHEMA TablePrivilege = "TABLE_ADD_SCHEMA"
	TABLEPRIVILEGE_TABLE_SET_CURRENT_SCHEMA TablePrivilege = "TABLE_SET_CURRENT_SCHEMA"
	TABLEPRIVILEGE_TABLE_ADD_PARTITION_SPEC TablePrivilege = "TABLE_ADD_PARTITION_SPEC"
	TABLEPRIVILEGE_TABLE_ADD_SORT_ORDER TablePrivilege = "TABLE_ADD_SORT_ORDER"
	TABLEPRIVILEGE_TABLE_SET_DEFAULT_SORT_ORDER TablePrivilege = "TABLE_SET_DEFAULT_SORT_ORDER"
	TABLEPRIVILEGE_TABLE_ADD_SNAPSHOT TablePrivilege = "TABLE_ADD_SNAPSHOT"
	TABLEPRIVILEGE_TABLE_SET_SNAPSHOT_REF TablePrivilege = "TABLE_SET_SNAPSHOT_REF"
	TABLEPRIVILEGE_TABLE_REMOVE_SNAPSHOTS TablePrivilege = "TABLE_REMOVE_SNAPSHOTS"
	TABLEPRIVILEGE_TABLE_REMOVE_SNAPSHOT_REF TablePrivilege = "TABLE_REMOVE_SNAPSHOT_REF"
	TABLEPRIVILEGE_TABLE_SET_LOCATION TablePrivilege = "TABLE_SET_LOCATION"
	TABLEPRIVILEGE_TABLE_SET_PROPERTIES TablePrivilege = "TABLE_SET_PROPERTIES"
	TABLEPRIVILEGE_TABLE_REMOVE_PROPERTIES TablePrivilege = "TABLE_REMOVE_PROPERTIES"
	TABLEPRIVILEGE_TABLE_SET_STATISTICS TablePrivilege = "TABLE_SET_STATISTICS"
	TABLEPRIVILEGE_TABLE_REMOVE_STATISTICS TablePrivilege = "TABLE_REMOVE_STATISTICS"
	TABLEPRIVILEGE_TABLE_REMOVE_PARTITION_SPECS TablePrivilege = "TABLE_REMOVE_PARTITION_SPECS"
	TABLEPRIVILEGE_TABLE_MANAGE_STRUCTURE TablePrivilege = "TABLE_MANAGE_STRUCTURE"
)

// All allowed values of TablePrivilege enum
var AllowedTablePrivilegeEnumValues = []TablePrivilege{
	"CATALOG_MANAGE_ACCESS",
	"TABLE_DROP",
	"TABLE_LIST",
	"TABLE_READ_PROPERTIES",
	"TABLE_WRITE_PROPERTIES",
	"TABLE_READ_DATA",
	"TABLE_WRITE_DATA",
	"TABLE_FULL_METADATA",
	"TABLE_ATTACH_POLICY",
	"TABLE_DETACH_POLICY",
	"TABLE_ASSIGN_UUID",
	"TABLE_UPGRADE_FORMAT_VERSION",
	"TABLE_ADD_SCHEMA",
	"TABLE_SET_CURRENT_SCHEMA",
	"TABLE_ADD_PARTITION_SPEC",
	"TABLE_ADD_SORT_ORDER",
	"TABLE_SET_DEFAULT_SORT_ORDER",
	"TABLE_ADD_SNAPSHOT",
	"TABLE_SET_SNAPSHOT_REF",
	"TABLE_REMOVE_SNAPSHOTS",
	"TABLE_REMOVE_SNAPSHOT_REF",
	"TABLE_SET_LOCATION",
	"TABLE_SET_PROPERTIES",
	"TABLE_REMOVE_PROPERTIES",
	"TABLE_SET_STATISTICS",
	"TABLE_REMOVE_STATISTICS",
	"TABLE_REMOVE_PARTITION_SPECS",
	"TABLE_MANAGE_STRUCTURE",
}

func (v *TablePrivilege) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TablePrivilege(value)
	for _, existing := range AllowedTablePrivilegeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TablePrivilege", value)
}

// NewTablePrivilegeFromValue returns a pointer to a valid TablePrivilege
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTablePrivilegeFromValue(v string) (*TablePrivilege, error) {
	ev := TablePrivilege(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TablePrivilege: valid values are %v", v, AllowedTablePrivilegeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TablePrivilege) IsValid() bool {
	for _, existing := range AllowedTablePrivilegeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TablePrivilege value
func (v TablePrivilege) Ptr() *TablePrivilege {
	return &v
}

type NullableTablePrivilege struct {
	value *TablePrivilege
	isSet bool
}

func (v NullableTablePrivilege) Get() *TablePrivilege {
	return v.value
}

func (v *NullableTablePrivilege) Set(val *TablePrivilege) {
	v.value = val
	v.isSet = true
}

func (v NullableTablePrivilege) IsSet() bool {
	return v.isSet
}

func (v *NullableTablePrivilege) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTablePrivilege(val *TablePrivilege) *NullableTablePrivilege {
	return &NullableTablePrivilege{value: val, isSet: true}
}

func (v NullableTablePrivilege) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTablePrivilege) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

