/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthenticationParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthenticationParameters{}

// AuthenticationParameters Authentication-specific information for a connection
type AuthenticationParameters struct {
	// The type of authentication to use when connecting to the remote rest service
	AuthenticationType string `json:"authenticationType"`
	AdditionalProperties map[string]interface{}
}

type _AuthenticationParameters AuthenticationParameters

// NewAuthenticationParameters instantiates a new AuthenticationParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticationParameters(authenticationType string) *AuthenticationParameters {
	this := AuthenticationParameters{}
	this.AuthenticationType = authenticationType
	return &this
}

// NewAuthenticationParametersWithDefaults instantiates a new AuthenticationParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticationParametersWithDefaults() *AuthenticationParameters {
	this := AuthenticationParameters{}
	return &this
}

// GetAuthenticationType returns the AuthenticationType field value
func (o *AuthenticationParameters) GetAuthenticationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticationType
}

// GetAuthenticationTypeOk returns a tuple with the AuthenticationType field value
// and a boolean to check if the value has been set.
func (o *AuthenticationParameters) GetAuthenticationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationType, true
}

// SetAuthenticationType sets field value
func (o *AuthenticationParameters) SetAuthenticationType(v string) {
	o.AuthenticationType = v
}

func (o AuthenticationParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthenticationParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authenticationType"] = o.AuthenticationType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthenticationParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authenticationType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthenticationParameters := _AuthenticationParameters{}

	err = json.Unmarshal(data, &varAuthenticationParameters)

	if err != nil {
		return err
	}

	*o = AuthenticationParameters(varAuthenticationParameters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authenticationType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthenticationParameters struct {
	value *AuthenticationParameters
	isSet bool
}

func (v NullableAuthenticationParameters) Get() *AuthenticationParameters {
	return v.value
}

func (v *NullableAuthenticationParameters) Set(val *AuthenticationParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticationParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticationParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticationParameters(val *AuthenticationParameters) *NullableAuthenticationParameters {
	return &NullableAuthenticationParameters{value: val, isSet: true}
}

func (v NullableAuthenticationParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticationParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


