/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the CatalogProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogProperties{}

// CatalogProperties struct for CatalogProperties
type CatalogProperties struct {
	DefaultBaseLocation  string `json:"default-base-location"`
	AdditionalProperties map[string]interface{}
}

type _CatalogProperties CatalogProperties

// NewCatalogProperties instantiates a new CatalogProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogProperties(defaultBaseLocation string) *CatalogProperties {
	this := CatalogProperties{}
	this.DefaultBaseLocation = defaultBaseLocation
	return &this
}

// NewCatalogPropertiesWithDefaults instantiates a new CatalogProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogPropertiesWithDefaults() *CatalogProperties {
	this := CatalogProperties{}
	return &this
}

// GetDefaultBaseLocation returns the DefaultBaseLocation field value
func (o *CatalogProperties) GetDefaultBaseLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultBaseLocation
}

// GetDefaultBaseLocationOk returns a tuple with the DefaultBaseLocation field value
// and a boolean to check if the value has been set.
func (o *CatalogProperties) GetDefaultBaseLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultBaseLocation, true
}

// SetDefaultBaseLocation sets field value
func (o *CatalogProperties) SetDefaultBaseLocation(v string) {
	o.DefaultBaseLocation = v
}

func (o CatalogProperties) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default-base-location"] = o.DefaultBaseLocation

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CatalogProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default-base-location",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogProperties := _CatalogProperties{}

	err = json.Unmarshal(data, &varCatalogProperties)

	if err != nil {
		return err
	}

	*o = CatalogProperties(varCatalogProperties)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "default-base-location")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCatalogProperties struct {
	value *CatalogProperties
	isSet bool
}

func (v NullableCatalogProperties) Get() *CatalogProperties {
	return v.value
}

func (v *NullableCatalogProperties) Set(val *CatalogProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogProperties(val *CatalogProperties) *NullableCatalogProperties {
	return &NullableCatalogProperties{value: val, isSet: true}
}

func (v NullableCatalogProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
