/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the OAuthClientCredentialsParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuthClientCredentialsParameters{}

// OAuthClientCredentialsParameters struct for OAuthClientCredentialsParameters
type OAuthClientCredentialsParameters struct {
	AuthenticationParameters
	// Token server URI
	TokenUri *string `json:"tokenUri,omitempty"`
	// oauth client id
	ClientId *string `json:"clientId,omitempty"`
	// oauth client secret (input-only)
	ClientSecret *string `json:"clientSecret,omitempty"`
	// oauth scopes to specify when exchanging for a short-lived access token
	Scopes []string `json:"scopes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OAuthClientCredentialsParameters OAuthClientCredentialsParameters

// NewOAuthClientCredentialsParameters instantiates a new OAuthClientCredentialsParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthClientCredentialsParameters(authenticationType string) *OAuthClientCredentialsParameters {
	this := OAuthClientCredentialsParameters{}
	this.AuthenticationType = authenticationType
	return &this
}

// NewOAuthClientCredentialsParametersWithDefaults instantiates a new OAuthClientCredentialsParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthClientCredentialsParametersWithDefaults() *OAuthClientCredentialsParameters {
	this := OAuthClientCredentialsParameters{}
	return &this
}

// GetTokenUri returns the TokenUri field value if set, zero value otherwise.
func (o *OAuthClientCredentialsParameters) GetTokenUri() string {
	if o == nil || IsNil(o.TokenUri) {
		var ret string
		return ret
	}
	return *o.TokenUri
}

// GetTokenUriOk returns a tuple with the TokenUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthClientCredentialsParameters) GetTokenUriOk() (*string, bool) {
	if o == nil || IsNil(o.TokenUri) {
		return nil, false
	}
	return o.TokenUri, true
}

// HasTokenUri returns a boolean if a field has been set.
func (o *OAuthClientCredentialsParameters) HasTokenUri() bool {
	if o != nil && !IsNil(o.TokenUri) {
		return true
	}

	return false
}

// SetTokenUri gets a reference to the given string and assigns it to the TokenUri field.
func (o *OAuthClientCredentialsParameters) SetTokenUri(v string) {
	o.TokenUri = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *OAuthClientCredentialsParameters) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthClientCredentialsParameters) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *OAuthClientCredentialsParameters) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *OAuthClientCredentialsParameters) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *OAuthClientCredentialsParameters) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthClientCredentialsParameters) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *OAuthClientCredentialsParameters) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *OAuthClientCredentialsParameters) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *OAuthClientCredentialsParameters) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthClientCredentialsParameters) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *OAuthClientCredentialsParameters) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *OAuthClientCredentialsParameters) SetScopes(v []string) {
	o.Scopes = v
}

func (o OAuthClientCredentialsParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuthClientCredentialsParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TokenUri) {
		toSerialize["tokenUri"] = o.TokenUri
	}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OAuthClientCredentialsParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authenticationType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOAuthClientCredentialsParameters := _OAuthClientCredentialsParameters{}

	err = json.Unmarshal(data, &varOAuthClientCredentialsParameters)

	if err != nil {
		return err
	}

	*o = OAuthClientCredentialsParameters(varOAuthClientCredentialsParameters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tokenUri")
		delete(additionalProperties, "clientId")
		delete(additionalProperties, "clientSecret")
		delete(additionalProperties, "scopes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOAuthClientCredentialsParameters struct {
	value *OAuthClientCredentialsParameters
	isSet bool
}

func (v NullableOAuthClientCredentialsParameters) Get() *OAuthClientCredentialsParameters {
	return v.value
}

func (v *NullableOAuthClientCredentialsParameters) Set(val *OAuthClientCredentialsParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthClientCredentialsParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthClientCredentialsParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthClientCredentialsParameters(val *OAuthClientCredentialsParameters) *NullableOAuthClientCredentialsParameters {
	return &NullableOAuthClientCredentialsParameters{value: val, isSet: true}
}

func (v NullableOAuthClientCredentialsParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthClientCredentialsParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


