/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the RevokeGrantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevokeGrantRequest{}

// RevokeGrantRequest struct for RevokeGrantRequest
type RevokeGrantRequest struct {
	Grant                *GrantResource `json:"grant,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RevokeGrantRequest RevokeGrantRequest

// NewRevokeGrantRequest instantiates a new RevokeGrantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevokeGrantRequest() *RevokeGrantRequest {
	this := RevokeGrantRequest{}
	return &this
}

// NewRevokeGrantRequestWithDefaults instantiates a new RevokeGrantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevokeGrantRequestWithDefaults() *RevokeGrantRequest {
	this := RevokeGrantRequest{}
	return &this
}

// GetGrant returns the Grant field value if set, zero value otherwise.
func (o *RevokeGrantRequest) GetGrant() GrantResource {
	if o == nil || IsNil(o.Grant) {
		var ret GrantResource
		return ret
	}
	return *o.Grant
}

// GetGrantOk returns a tuple with the Grant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeGrantRequest) GetGrantOk() (*GrantResource, bool) {
	if o == nil || IsNil(o.Grant) {
		return nil, false
	}
	return o.Grant, true
}

// HasGrant returns a boolean if a field has been set.
func (o *RevokeGrantRequest) HasGrant() bool {
	if o != nil && !IsNil(o.Grant) {
		return true
	}

	return false
}

// SetGrant gets a reference to the given GrantResource and assigns it to the Grant field.
func (o *RevokeGrantRequest) SetGrant(v GrantResource) {
	o.Grant = &v
}

func (o RevokeGrantRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevokeGrantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Grant) {
		toSerialize["grant"] = o.Grant
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RevokeGrantRequest) UnmarshalJSON(data []byte) (err error) {
	varRevokeGrantRequest := _RevokeGrantRequest{}

	err = json.Unmarshal(data, &varRevokeGrantRequest)

	if err != nil {
		return err
	}

	*o = RevokeGrantRequest(varRevokeGrantRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "grant")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRevokeGrantRequest struct {
	value *RevokeGrantRequest
	isSet bool
}

func (v NullableRevokeGrantRequest) Get() *RevokeGrantRequest {
	return v.value
}

func (v *NullableRevokeGrantRequest) Set(val *RevokeGrantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRevokeGrantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRevokeGrantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevokeGrantRequest(val *RevokeGrantRequest) *NullableRevokeGrantRequest {
	return &NullableRevokeGrantRequest{value: val, isSet: true}
}

func (v NullableRevokeGrantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevokeGrantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
