/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the CreatePrincipalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePrincipalRequest{}

// CreatePrincipalRequest struct for CreatePrincipalRequest
type CreatePrincipalRequest struct {
	Principal *Principal `json:"principal,omitempty"`
	// If true, the initial credentials can only be used to call rotateCredentials
	CredentialRotationRequired *bool `json:"credentialRotationRequired,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreatePrincipalRequest CreatePrincipalRequest

// NewCreatePrincipalRequest instantiates a new CreatePrincipalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePrincipalRequest() *CreatePrincipalRequest {
	this := CreatePrincipalRequest{}
	return &this
}

// NewCreatePrincipalRequestWithDefaults instantiates a new CreatePrincipalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePrincipalRequestWithDefaults() *CreatePrincipalRequest {
	this := CreatePrincipalRequest{}
	return &this
}

// GetPrincipal returns the Principal field value if set, zero value otherwise.
func (o *CreatePrincipalRequest) GetPrincipal() Principal {
	if o == nil || IsNil(o.Principal) {
		var ret Principal
		return ret
	}
	return *o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrincipalRequest) GetPrincipalOk() (*Principal, bool) {
	if o == nil || IsNil(o.Principal) {
		return nil, false
	}
	return o.Principal, true
}

// HasPrincipal returns a boolean if a field has been set.
func (o *CreatePrincipalRequest) HasPrincipal() bool {
	if o != nil && !IsNil(o.Principal) {
		return true
	}

	return false
}

// SetPrincipal gets a reference to the given Principal and assigns it to the Principal field.
func (o *CreatePrincipalRequest) SetPrincipal(v Principal) {
	o.Principal = &v
}

// GetCredentialRotationRequired returns the CredentialRotationRequired field value if set, zero value otherwise.
func (o *CreatePrincipalRequest) GetCredentialRotationRequired() bool {
	if o == nil || IsNil(o.CredentialRotationRequired) {
		var ret bool
		return ret
	}
	return *o.CredentialRotationRequired
}

// GetCredentialRotationRequiredOk returns a tuple with the CredentialRotationRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrincipalRequest) GetCredentialRotationRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.CredentialRotationRequired) {
		return nil, false
	}
	return o.CredentialRotationRequired, true
}

// HasCredentialRotationRequired returns a boolean if a field has been set.
func (o *CreatePrincipalRequest) HasCredentialRotationRequired() bool {
	if o != nil && !IsNil(o.CredentialRotationRequired) {
		return true
	}

	return false
}

// SetCredentialRotationRequired gets a reference to the given bool and assigns it to the CredentialRotationRequired field.
func (o *CreatePrincipalRequest) SetCredentialRotationRequired(v bool) {
	o.CredentialRotationRequired = &v
}

func (o CreatePrincipalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePrincipalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Principal) {
		toSerialize["principal"] = o.Principal
	}
	if !IsNil(o.CredentialRotationRequired) {
		toSerialize["credentialRotationRequired"] = o.CredentialRotationRequired
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreatePrincipalRequest) UnmarshalJSON(data []byte) (err error) {
	varCreatePrincipalRequest := _CreatePrincipalRequest{}

	err = json.Unmarshal(data, &varCreatePrincipalRequest)

	if err != nil {
		return err
	}

	*o = CreatePrincipalRequest(varCreatePrincipalRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "principal")
		delete(additionalProperties, "credentialRotationRequired")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreatePrincipalRequest struct {
	value *CreatePrincipalRequest
	isSet bool
}

func (v NullableCreatePrincipalRequest) Get() *CreatePrincipalRequest {
	return v.value
}

func (v *NullableCreatePrincipalRequest) Set(val *CreatePrincipalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePrincipalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePrincipalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePrincipalRequest(val *CreatePrincipalRequest) *NullableCreatePrincipalRequest {
	return &NullableCreatePrincipalRequest{value: val, isSet: true}
}

func (v NullableCreatePrincipalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePrincipalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


