/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the CreatePrincipalRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePrincipalRoleRequest{}

// CreatePrincipalRoleRequest struct for CreatePrincipalRoleRequest
type CreatePrincipalRoleRequest struct {
	PrincipalRole        *PrincipalRole `json:"principalRole,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreatePrincipalRoleRequest CreatePrincipalRoleRequest

// NewCreatePrincipalRoleRequest instantiates a new CreatePrincipalRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePrincipalRoleRequest() *CreatePrincipalRoleRequest {
	this := CreatePrincipalRoleRequest{}
	return &this
}

// NewCreatePrincipalRoleRequestWithDefaults instantiates a new CreatePrincipalRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePrincipalRoleRequestWithDefaults() *CreatePrincipalRoleRequest {
	this := CreatePrincipalRoleRequest{}
	return &this
}

// GetPrincipalRole returns the PrincipalRole field value if set, zero value otherwise.
func (o *CreatePrincipalRoleRequest) GetPrincipalRole() PrincipalRole {
	if o == nil || IsNil(o.PrincipalRole) {
		var ret PrincipalRole
		return ret
	}
	return *o.PrincipalRole
}

// GetPrincipalRoleOk returns a tuple with the PrincipalRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrincipalRoleRequest) GetPrincipalRoleOk() (*PrincipalRole, bool) {
	if o == nil || IsNil(o.PrincipalRole) {
		return nil, false
	}
	return o.PrincipalRole, true
}

// HasPrincipalRole returns a boolean if a field has been set.
func (o *CreatePrincipalRoleRequest) HasPrincipalRole() bool {
	if o != nil && !IsNil(o.PrincipalRole) {
		return true
	}

	return false
}

// SetPrincipalRole gets a reference to the given PrincipalRole and assigns it to the PrincipalRole field.
func (o *CreatePrincipalRoleRequest) SetPrincipalRole(v PrincipalRole) {
	o.PrincipalRole = &v
}

func (o CreatePrincipalRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePrincipalRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrincipalRole) {
		toSerialize["principalRole"] = o.PrincipalRole
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreatePrincipalRoleRequest) UnmarshalJSON(data []byte) (err error) {
	varCreatePrincipalRoleRequest := _CreatePrincipalRoleRequest{}

	err = json.Unmarshal(data, &varCreatePrincipalRoleRequest)

	if err != nil {
		return err
	}

	*o = CreatePrincipalRoleRequest(varCreatePrincipalRoleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "principalRole")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreatePrincipalRoleRequest struct {
	value *CreatePrincipalRoleRequest
	isSet bool
}

func (v NullableCreatePrincipalRoleRequest) Get() *CreatePrincipalRoleRequest {
	return v.value
}

func (v *NullableCreatePrincipalRoleRequest) Set(val *CreatePrincipalRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePrincipalRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePrincipalRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePrincipalRoleRequest(val *CreatePrincipalRoleRequest) *NullableCreatePrincipalRoleRequest {
	return &NullableCreatePrincipalRoleRequest{value: val, isSet: true}
}

func (v NullableCreatePrincipalRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePrincipalRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
