/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the HiveConnectionConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HiveConnectionConfigInfo{}

// HiveConnectionConfigInfo struct for HiveConnectionConfigInfo
type HiveConnectionConfigInfo struct {
	ConnectionConfigInfo
	// The warehouse location for the hive catalog.
	Warehouse            *string `json:"warehouse,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HiveConnectionConfigInfo HiveConnectionConfigInfo

// NewHiveConnectionConfigInfo instantiates a new HiveConnectionConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHiveConnectionConfigInfo(connectionType string) *HiveConnectionConfigInfo {
	this := HiveConnectionConfigInfo{}
	this.ConnectionType = connectionType
	return &this
}

// NewHiveConnectionConfigInfoWithDefaults instantiates a new HiveConnectionConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHiveConnectionConfigInfoWithDefaults() *HiveConnectionConfigInfo {
	this := HiveConnectionConfigInfo{}
	return &this
}

// GetWarehouse returns the Warehouse field value if set, zero value otherwise.
func (o *HiveConnectionConfigInfo) GetWarehouse() string {
	if o == nil || IsNil(o.Warehouse) {
		var ret string
		return ret
	}
	return *o.Warehouse
}

// GetWarehouseOk returns a tuple with the Warehouse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HiveConnectionConfigInfo) GetWarehouseOk() (*string, bool) {
	if o == nil || IsNil(o.Warehouse) {
		return nil, false
	}
	return o.Warehouse, true
}

// HasWarehouse returns a boolean if a field has been set.
func (o *HiveConnectionConfigInfo) HasWarehouse() bool {
	if o != nil && !IsNil(o.Warehouse) {
		return true
	}

	return false
}

// SetWarehouse gets a reference to the given string and assigns it to the Warehouse field.
func (o *HiveConnectionConfigInfo) SetWarehouse(v string) {
	o.Warehouse = &v
}

func (o HiveConnectionConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HiveConnectionConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Warehouse) {
		toSerialize["warehouse"] = o.Warehouse
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HiveConnectionConfigInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectionType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHiveConnectionConfigInfo := _HiveConnectionConfigInfo{}

	err = json.Unmarshal(data, &varHiveConnectionConfigInfo)

	if err != nil {
		return err
	}

	*o = HiveConnectionConfigInfo(varHiveConnectionConfigInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "warehouse")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHiveConnectionConfigInfo struct {
	value *HiveConnectionConfigInfo
	isSet bool
}

func (v NullableHiveConnectionConfigInfo) Get() *HiveConnectionConfigInfo {
	return v.value
}

func (v *NullableHiveConnectionConfigInfo) Set(val *HiveConnectionConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableHiveConnectionConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableHiveConnectionConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHiveConnectionConfigInfo(val *HiveConnectionConfigInfo) *NullableHiveConnectionConfigInfo {
	return &NullableHiveConnectionConfigInfo{value: val, isSet: true}
}

func (v NullableHiveConnectionConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHiveConnectionConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
