/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the PrincipalRoles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrincipalRoles{}

// PrincipalRoles struct for PrincipalRoles
type PrincipalRoles struct {
	Roles []PrincipalRole `json:"roles"`
	AdditionalProperties map[string]interface{}
}

type _PrincipalRoles PrincipalRoles

// NewPrincipalRoles instantiates a new PrincipalRoles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipalRoles(roles []PrincipalRole) *PrincipalRoles {
	this := PrincipalRoles{}
	this.Roles = roles
	return &this
}

// NewPrincipalRolesWithDefaults instantiates a new PrincipalRoles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalRolesWithDefaults() *PrincipalRoles {
	this := PrincipalRoles{}
	return &this
}

// GetRoles returns the Roles field value
func (o *PrincipalRoles) GetRoles() []PrincipalRole {
	if o == nil {
		var ret []PrincipalRole
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *PrincipalRoles) GetRolesOk() ([]PrincipalRole, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *PrincipalRoles) SetRoles(v []PrincipalRole) {
	o.Roles = v
}

func (o PrincipalRoles) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrincipalRoles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roles"] = o.Roles

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrincipalRoles) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrincipalRoles := _PrincipalRoles{}

	err = json.Unmarshal(data, &varPrincipalRoles)

	if err != nil {
		return err
	}

	*o = PrincipalRoles(varPrincipalRoles)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "roles")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrincipalRoles struct {
	value *PrincipalRoles
	isSet bool
}

func (v NullablePrincipalRoles) Get() *PrincipalRoles {
	return v.value
}

func (v *NullablePrincipalRoles) Set(val *PrincipalRoles) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipalRoles) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipalRoles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipalRoles(val *PrincipalRoles) *NullablePrincipalRoles {
	return &NullablePrincipalRoles{value: val, isSet: true}
}

func (v NullablePrincipalRoles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipalRoles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


