/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the BearerAuthenticationParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BearerAuthenticationParameters{}

// BearerAuthenticationParameters struct for BearerAuthenticationParameters
type BearerAuthenticationParameters struct {
	AuthenticationParameters
	// Bearer token (input-only)
	BearerToken *string `json:"bearerToken,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BearerAuthenticationParameters BearerAuthenticationParameters

// NewBearerAuthenticationParameters instantiates a new BearerAuthenticationParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBearerAuthenticationParameters(authenticationType string) *BearerAuthenticationParameters {
	this := BearerAuthenticationParameters{}
	this.AuthenticationType = authenticationType
	return &this
}

// NewBearerAuthenticationParametersWithDefaults instantiates a new BearerAuthenticationParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBearerAuthenticationParametersWithDefaults() *BearerAuthenticationParameters {
	this := BearerAuthenticationParameters{}
	return &this
}

// GetBearerToken returns the BearerToken field value if set, zero value otherwise.
func (o *BearerAuthenticationParameters) GetBearerToken() string {
	if o == nil || IsNil(o.BearerToken) {
		var ret string
		return ret
	}
	return *o.BearerToken
}

// GetBearerTokenOk returns a tuple with the BearerToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BearerAuthenticationParameters) GetBearerTokenOk() (*string, bool) {
	if o == nil || IsNil(o.BearerToken) {
		return nil, false
	}
	return o.BearerToken, true
}

// HasBearerToken returns a boolean if a field has been set.
func (o *BearerAuthenticationParameters) HasBearerToken() bool {
	if o != nil && !IsNil(o.BearerToken) {
		return true
	}

	return false
}

// SetBearerToken gets a reference to the given string and assigns it to the BearerToken field.
func (o *BearerAuthenticationParameters) SetBearerToken(v string) {
	o.BearerToken = &v
}

func (o BearerAuthenticationParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BearerAuthenticationParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BearerToken) {
		toSerialize["bearerToken"] = o.BearerToken
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BearerAuthenticationParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authenticationType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBearerAuthenticationParameters := _BearerAuthenticationParameters{}

	err = json.Unmarshal(data, &varBearerAuthenticationParameters)

	if err != nil {
		return err
	}

	*o = BearerAuthenticationParameters(varBearerAuthenticationParameters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bearerToken")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBearerAuthenticationParameters struct {
	value *BearerAuthenticationParameters
	isSet bool
}

func (v NullableBearerAuthenticationParameters) Get() *BearerAuthenticationParameters {
	return v.value
}

func (v *NullableBearerAuthenticationParameters) Set(val *BearerAuthenticationParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableBearerAuthenticationParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableBearerAuthenticationParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBearerAuthenticationParameters(val *BearerAuthenticationParameters) *NullableBearerAuthenticationParameters {
	return &NullableBearerAuthenticationParameters{value: val, isSet: true}
}

func (v NullableBearerAuthenticationParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBearerAuthenticationParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


