/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the Catalogs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Catalogs{}

// Catalogs A list of Catalog objects
type Catalogs struct {
	Catalogs             []Catalog `json:"catalogs"`
	AdditionalProperties map[string]interface{}
}

type _Catalogs Catalogs

// NewCatalogs instantiates a new Catalogs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogs(catalogs []Catalog) *Catalogs {
	this := Catalogs{}
	this.Catalogs = catalogs
	return &this
}

// NewCatalogsWithDefaults instantiates a new Catalogs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogsWithDefaults() *Catalogs {
	this := Catalogs{}
	return &this
}

// GetCatalogs returns the Catalogs field value
func (o *Catalogs) GetCatalogs() []Catalog {
	if o == nil {
		var ret []Catalog
		return ret
	}

	return o.Catalogs
}

// GetCatalogsOk returns a tuple with the Catalogs field value
// and a boolean to check if the value has been set.
func (o *Catalogs) GetCatalogsOk() ([]Catalog, bool) {
	if o == nil {
		return nil, false
	}
	return o.Catalogs, true
}

// SetCatalogs sets field value
func (o *Catalogs) SetCatalogs(v []Catalog) {
	o.Catalogs = v
}

func (o Catalogs) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Catalogs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["catalogs"] = o.Catalogs

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Catalogs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"catalogs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogs := _Catalogs{}

	err = json.Unmarshal(data, &varCatalogs)

	if err != nil {
		return err
	}

	*o = Catalogs(varCatalogs)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "catalogs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCatalogs struct {
	value *Catalogs
	isSet bool
}

func (v NullableCatalogs) Get() *Catalogs {
	return v.value
}

func (v *NullableCatalogs) Set(val *Catalogs) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogs) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogs(val *Catalogs) *NullableCatalogs {
	return &NullableCatalogs{value: val, isSet: true}
}

func (v NullableCatalogs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
