/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the GrantCatalogRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantCatalogRoleRequest{}

// GrantCatalogRoleRequest struct for GrantCatalogRoleRequest
type GrantCatalogRoleRequest struct {
	CatalogRole          *CatalogRole `json:"catalogRole,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GrantCatalogRoleRequest GrantCatalogRoleRequest

// NewGrantCatalogRoleRequest instantiates a new GrantCatalogRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantCatalogRoleRequest() *GrantCatalogRoleRequest {
	this := GrantCatalogRoleRequest{}
	return &this
}

// NewGrantCatalogRoleRequestWithDefaults instantiates a new GrantCatalogRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantCatalogRoleRequestWithDefaults() *GrantCatalogRoleRequest {
	this := GrantCatalogRoleRequest{}
	return &this
}

// GetCatalogRole returns the CatalogRole field value if set, zero value otherwise.
func (o *GrantCatalogRoleRequest) GetCatalogRole() CatalogRole {
	if o == nil || IsNil(o.CatalogRole) {
		var ret CatalogRole
		return ret
	}
	return *o.CatalogRole
}

// GetCatalogRoleOk returns a tuple with the CatalogRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GrantCatalogRoleRequest) GetCatalogRoleOk() (*CatalogRole, bool) {
	if o == nil || IsNil(o.CatalogRole) {
		return nil, false
	}
	return o.CatalogRole, true
}

// HasCatalogRole returns a boolean if a field has been set.
func (o *GrantCatalogRoleRequest) HasCatalogRole() bool {
	if o != nil && !IsNil(o.CatalogRole) {
		return true
	}

	return false
}

// SetCatalogRole gets a reference to the given CatalogRole and assigns it to the CatalogRole field.
func (o *GrantCatalogRoleRequest) SetCatalogRole(v CatalogRole) {
	o.CatalogRole = &v
}

func (o GrantCatalogRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantCatalogRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CatalogRole) {
		toSerialize["catalogRole"] = o.CatalogRole
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GrantCatalogRoleRequest) UnmarshalJSON(data []byte) (err error) {
	varGrantCatalogRoleRequest := _GrantCatalogRoleRequest{}

	err = json.Unmarshal(data, &varGrantCatalogRoleRequest)

	if err != nil {
		return err
	}

	*o = GrantCatalogRoleRequest(varGrantCatalogRoleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "catalogRole")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGrantCatalogRoleRequest struct {
	value *GrantCatalogRoleRequest
	isSet bool
}

func (v NullableGrantCatalogRoleRequest) Get() *GrantCatalogRoleRequest {
	return v.value
}

func (v *NullableGrantCatalogRoleRequest) Set(val *GrantCatalogRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantCatalogRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantCatalogRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantCatalogRoleRequest(val *GrantCatalogRoleRequest) *NullableGrantCatalogRoleRequest {
	return &NullableGrantCatalogRoleRequest{value: val, isSet: true}
}

func (v NullableGrantCatalogRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantCatalogRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
