/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the SigV4AuthenticationParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SigV4AuthenticationParameters{}

// SigV4AuthenticationParameters struct for SigV4AuthenticationParameters
type SigV4AuthenticationParameters struct {
	AuthenticationParameters
	// The aws IAM role arn assumed by polaris userArn when signing requests
	RoleArn string `json:"roleArn"`
	// The role session name to be used by the SigV4 protocol for signing requests
	RoleSessionName *string `json:"roleSessionName,omitempty"`
	// An optional external id used to establish a trust relationship with AWS in the trust policy
	ExternalId *string `json:"externalId,omitempty"`
	// Region to be used by the SigV4 protocol for signing requests
	SigningRegion string `json:"signingRegion"`
	// The service name to be used by the SigV4 protocol for signing requests, the default signing name is \"execute-api\" is if not provided
	SigningName *string `json:"signingName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SigV4AuthenticationParameters SigV4AuthenticationParameters

// NewSigV4AuthenticationParameters instantiates a new SigV4AuthenticationParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSigV4AuthenticationParameters(roleArn string, signingRegion string, authenticationType string) *SigV4AuthenticationParameters {
	this := SigV4AuthenticationParameters{}
	this.AuthenticationType = authenticationType
	this.RoleArn = roleArn
	this.SigningRegion = signingRegion
	return &this
}

// NewSigV4AuthenticationParametersWithDefaults instantiates a new SigV4AuthenticationParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSigV4AuthenticationParametersWithDefaults() *SigV4AuthenticationParameters {
	this := SigV4AuthenticationParameters{}
	return &this
}

// GetRoleArn returns the RoleArn field value
func (o *SigV4AuthenticationParameters) GetRoleArn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value
// and a boolean to check if the value has been set.
func (o *SigV4AuthenticationParameters) GetRoleArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleArn, true
}

// SetRoleArn sets field value
func (o *SigV4AuthenticationParameters) SetRoleArn(v string) {
	o.RoleArn = v
}

// GetRoleSessionName returns the RoleSessionName field value if set, zero value otherwise.
func (o *SigV4AuthenticationParameters) GetRoleSessionName() string {
	if o == nil || IsNil(o.RoleSessionName) {
		var ret string
		return ret
	}
	return *o.RoleSessionName
}

// GetRoleSessionNameOk returns a tuple with the RoleSessionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SigV4AuthenticationParameters) GetRoleSessionNameOk() (*string, bool) {
	if o == nil || IsNil(o.RoleSessionName) {
		return nil, false
	}
	return o.RoleSessionName, true
}

// HasRoleSessionName returns a boolean if a field has been set.
func (o *SigV4AuthenticationParameters) HasRoleSessionName() bool {
	if o != nil && !IsNil(o.RoleSessionName) {
		return true
	}

	return false
}

// SetRoleSessionName gets a reference to the given string and assigns it to the RoleSessionName field.
func (o *SigV4AuthenticationParameters) SetRoleSessionName(v string) {
	o.RoleSessionName = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *SigV4AuthenticationParameters) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SigV4AuthenticationParameters) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *SigV4AuthenticationParameters) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *SigV4AuthenticationParameters) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetSigningRegion returns the SigningRegion field value
func (o *SigV4AuthenticationParameters) GetSigningRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SigningRegion
}

// GetSigningRegionOk returns a tuple with the SigningRegion field value
// and a boolean to check if the value has been set.
func (o *SigV4AuthenticationParameters) GetSigningRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SigningRegion, true
}

// SetSigningRegion sets field value
func (o *SigV4AuthenticationParameters) SetSigningRegion(v string) {
	o.SigningRegion = v
}

// GetSigningName returns the SigningName field value if set, zero value otherwise.
func (o *SigV4AuthenticationParameters) GetSigningName() string {
	if o == nil || IsNil(o.SigningName) {
		var ret string
		return ret
	}
	return *o.SigningName
}

// GetSigningNameOk returns a tuple with the SigningName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SigV4AuthenticationParameters) GetSigningNameOk() (*string, bool) {
	if o == nil || IsNil(o.SigningName) {
		return nil, false
	}
	return o.SigningName, true
}

// HasSigningName returns a boolean if a field has been set.
func (o *SigV4AuthenticationParameters) HasSigningName() bool {
	if o != nil && !IsNil(o.SigningName) {
		return true
	}

	return false
}

// SetSigningName gets a reference to the given string and assigns it to the SigningName field.
func (o *SigV4AuthenticationParameters) SetSigningName(v string) {
	o.SigningName = &v
}

func (o SigV4AuthenticationParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SigV4AuthenticationParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roleArn"] = o.RoleArn
	if !IsNil(o.RoleSessionName) {
		toSerialize["roleSessionName"] = o.RoleSessionName
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	toSerialize["signingRegion"] = o.SigningRegion
	if !IsNil(o.SigningName) {
		toSerialize["signingName"] = o.SigningName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SigV4AuthenticationParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roleArn",
		"signingRegion",
		"authenticationType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSigV4AuthenticationParameters := _SigV4AuthenticationParameters{}

	err = json.Unmarshal(data, &varSigV4AuthenticationParameters)

	if err != nil {
		return err
	}

	*o = SigV4AuthenticationParameters(varSigV4AuthenticationParameters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "roleArn")
		delete(additionalProperties, "roleSessionName")
		delete(additionalProperties, "externalId")
		delete(additionalProperties, "signingRegion")
		delete(additionalProperties, "signingName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSigV4AuthenticationParameters struct {
	value *SigV4AuthenticationParameters
	isSet bool
}

func (v NullableSigV4AuthenticationParameters) Get() *SigV4AuthenticationParameters {
	return v.value
}

func (v *NullableSigV4AuthenticationParameters) Set(val *SigV4AuthenticationParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableSigV4AuthenticationParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableSigV4AuthenticationParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSigV4AuthenticationParameters(val *SigV4AuthenticationParameters) *NullableSigV4AuthenticationParameters {
	return &NullableSigV4AuthenticationParameters{value: val, isSet: true}
}

func (v NullableSigV4AuthenticationParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSigV4AuthenticationParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


