/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the CreateCatalogRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCatalogRoleRequest{}

// CreateCatalogRoleRequest struct for CreateCatalogRoleRequest
type CreateCatalogRoleRequest struct {
	CatalogRole          *CatalogRole `json:"catalogRole,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateCatalogRoleRequest CreateCatalogRoleRequest

// NewCreateCatalogRoleRequest instantiates a new CreateCatalogRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCatalogRoleRequest() *CreateCatalogRoleRequest {
	this := CreateCatalogRoleRequest{}
	return &this
}

// NewCreateCatalogRoleRequestWithDefaults instantiates a new CreateCatalogRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCatalogRoleRequestWithDefaults() *CreateCatalogRoleRequest {
	this := CreateCatalogRoleRequest{}
	return &this
}

// GetCatalogRole returns the CatalogRole field value if set, zero value otherwise.
func (o *CreateCatalogRoleRequest) GetCatalogRole() CatalogRole {
	if o == nil || IsNil(o.CatalogRole) {
		var ret CatalogRole
		return ret
	}
	return *o.CatalogRole
}

// GetCatalogRoleOk returns a tuple with the CatalogRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCatalogRoleRequest) GetCatalogRoleOk() (*CatalogRole, bool) {
	if o == nil || IsNil(o.CatalogRole) {
		return nil, false
	}
	return o.CatalogRole, true
}

// HasCatalogRole returns a boolean if a field has been set.
func (o *CreateCatalogRoleRequest) HasCatalogRole() bool {
	if o != nil && !IsNil(o.CatalogRole) {
		return true
	}

	return false
}

// SetCatalogRole gets a reference to the given CatalogRole and assigns it to the CatalogRole field.
func (o *CreateCatalogRoleRequest) SetCatalogRole(v CatalogRole) {
	o.CatalogRole = &v
}

func (o CreateCatalogRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCatalogRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CatalogRole) {
		toSerialize["catalogRole"] = o.CatalogRole
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateCatalogRoleRequest) UnmarshalJSON(data []byte) (err error) {
	varCreateCatalogRoleRequest := _CreateCatalogRoleRequest{}

	err = json.Unmarshal(data, &varCreateCatalogRoleRequest)

	if err != nil {
		return err
	}

	*o = CreateCatalogRoleRequest(varCreateCatalogRoleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "catalogRole")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateCatalogRoleRequest struct {
	value *CreateCatalogRoleRequest
	isSet bool
}

func (v NullableCreateCatalogRoleRequest) Get() *CreateCatalogRoleRequest {
	return v.value
}

func (v *NullableCreateCatalogRoleRequest) Set(val *CreateCatalogRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCatalogRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCatalogRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCatalogRoleRequest(val *CreateCatalogRoleRequest) *NullableCreateCatalogRoleRequest {
	return &NullableCreateCatalogRoleRequest{value: val, isSet: true}
}

func (v NullableCreateCatalogRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCatalogRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
