/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the UpdateCatalogRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCatalogRequest{}

// UpdateCatalogRequest Updates to apply to a Catalog. Any fields which are required in the Catalog will remain unaltered if omitted from the contents of this Update request.
type UpdateCatalogRequest struct {
	// The version of the object onto which this update is applied; if the object changed, the update will fail and the caller should retry after fetching the latest version.
	CurrentEntityVersion *int32             `json:"currentEntityVersion,omitempty"`
	Properties           *map[string]string `json:"properties,omitempty"`
	StorageConfigInfo    *StorageConfigInfo `json:"storageConfigInfo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateCatalogRequest UpdateCatalogRequest

// NewUpdateCatalogRequest instantiates a new UpdateCatalogRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCatalogRequest() *UpdateCatalogRequest {
	this := UpdateCatalogRequest{}
	return &this
}

// NewUpdateCatalogRequestWithDefaults instantiates a new UpdateCatalogRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCatalogRequestWithDefaults() *UpdateCatalogRequest {
	this := UpdateCatalogRequest{}
	return &this
}

// GetCurrentEntityVersion returns the CurrentEntityVersion field value if set, zero value otherwise.
func (o *UpdateCatalogRequest) GetCurrentEntityVersion() int32 {
	if o == nil || IsNil(o.CurrentEntityVersion) {
		var ret int32
		return ret
	}
	return *o.CurrentEntityVersion
}

// GetCurrentEntityVersionOk returns a tuple with the CurrentEntityVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCatalogRequest) GetCurrentEntityVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentEntityVersion) {
		return nil, false
	}
	return o.CurrentEntityVersion, true
}

// HasCurrentEntityVersion returns a boolean if a field has been set.
func (o *UpdateCatalogRequest) HasCurrentEntityVersion() bool {
	if o != nil && !IsNil(o.CurrentEntityVersion) {
		return true
	}

	return false
}

// SetCurrentEntityVersion gets a reference to the given int32 and assigns it to the CurrentEntityVersion field.
func (o *UpdateCatalogRequest) SetCurrentEntityVersion(v int32) {
	o.CurrentEntityVersion = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *UpdateCatalogRequest) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCatalogRequest) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *UpdateCatalogRequest) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *UpdateCatalogRequest) SetProperties(v map[string]string) {
	o.Properties = &v
}

// GetStorageConfigInfo returns the StorageConfigInfo field value if set, zero value otherwise.
func (o *UpdateCatalogRequest) GetStorageConfigInfo() StorageConfigInfo {
	if o == nil || IsNil(o.StorageConfigInfo) {
		var ret StorageConfigInfo
		return ret
	}
	return *o.StorageConfigInfo
}

// GetStorageConfigInfoOk returns a tuple with the StorageConfigInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCatalogRequest) GetStorageConfigInfoOk() (*StorageConfigInfo, bool) {
	if o == nil || IsNil(o.StorageConfigInfo) {
		return nil, false
	}
	return o.StorageConfigInfo, true
}

// HasStorageConfigInfo returns a boolean if a field has been set.
func (o *UpdateCatalogRequest) HasStorageConfigInfo() bool {
	if o != nil && !IsNil(o.StorageConfigInfo) {
		return true
	}

	return false
}

// SetStorageConfigInfo gets a reference to the given StorageConfigInfo and assigns it to the StorageConfigInfo field.
func (o *UpdateCatalogRequest) SetStorageConfigInfo(v StorageConfigInfo) {
	o.StorageConfigInfo = &v
}

func (o UpdateCatalogRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCatalogRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentEntityVersion) {
		toSerialize["currentEntityVersion"] = o.CurrentEntityVersion
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.StorageConfigInfo) {
		toSerialize["storageConfigInfo"] = o.StorageConfigInfo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateCatalogRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateCatalogRequest := _UpdateCatalogRequest{}

	err = json.Unmarshal(data, &varUpdateCatalogRequest)

	if err != nil {
		return err
	}

	*o = UpdateCatalogRequest(varUpdateCatalogRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "currentEntityVersion")
		delete(additionalProperties, "properties")
		delete(additionalProperties, "storageConfigInfo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateCatalogRequest struct {
	value *UpdateCatalogRequest
	isSet bool
}

func (v NullableUpdateCatalogRequest) Get() *UpdateCatalogRequest {
	return v.value
}

func (v *NullableUpdateCatalogRequest) Set(val *UpdateCatalogRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCatalogRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCatalogRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCatalogRequest(val *UpdateCatalogRequest) *NullableUpdateCatalogRequest {
	return &NullableUpdateCatalogRequest{value: val, isSet: true}
}

func (v NullableUpdateCatalogRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCatalogRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
