/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// CatalogPrivilege the model 'CatalogPrivilege'
type CatalogPrivilege string

// List of CatalogPrivilege
const (
	CATALOGPRIVILEGE_CATALOG_MANAGE_ACCESS        CatalogPrivilege = "CATALOG_MANAGE_ACCESS"
	CATALOGPRIVILEGE_CATALOG_MANAGE_CONTENT       CatalogPrivilege = "CATALOG_MANAGE_CONTENT"
	CATALOGPRIVILEGE_CATALOG_MANAGE_METADATA      CatalogPrivilege = "CATALOG_MANAGE_METADATA"
	CATALOGPRIVILEGE_CATALOG_READ_PROPERTIES      CatalogPrivilege = "CATALOG_READ_PROPERTIES"
	CATALOGPRIVILEGE_CATALOG_WRITE_PROPERTIES     CatalogPrivilege = "CATALOG_WRITE_PROPERTIES"
	CATALOGPRIVILEGE_NAMESPACE_CREATE             CatalogPrivilege = "NAMESPACE_CREATE"
	CATALOGPRIVILEGE_TABLE_CREATE                 CatalogPrivilege = "TABLE_CREATE"
	CATALOGPRIVILEGE_VIEW_CREATE                  CatalogPrivilege = "VIEW_CREATE"
	CATALOGPRIVILEGE_NAMESPACE_DROP               CatalogPrivilege = "NAMESPACE_DROP"
	CATALOGPRIVILEGE_TABLE_DROP                   CatalogPrivilege = "TABLE_DROP"
	CATALOGPRIVILEGE_VIEW_DROP                    CatalogPrivilege = "VIEW_DROP"
	CATALOGPRIVILEGE_NAMESPACE_LIST               CatalogPrivilege = "NAMESPACE_LIST"
	CATALOGPRIVILEGE_TABLE_LIST                   CatalogPrivilege = "TABLE_LIST"
	CATALOGPRIVILEGE_VIEW_LIST                    CatalogPrivilege = "VIEW_LIST"
	CATALOGPRIVILEGE_NAMESPACE_READ_PROPERTIES    CatalogPrivilege = "NAMESPACE_READ_PROPERTIES"
	CATALOGPRIVILEGE_TABLE_READ_PROPERTIES        CatalogPrivilege = "TABLE_READ_PROPERTIES"
	CATALOGPRIVILEGE_VIEW_READ_PROPERTIES         CatalogPrivilege = "VIEW_READ_PROPERTIES"
	CATALOGPRIVILEGE_NAMESPACE_WRITE_PROPERTIES   CatalogPrivilege = "NAMESPACE_WRITE_PROPERTIES"
	CATALOGPRIVILEGE_TABLE_WRITE_PROPERTIES       CatalogPrivilege = "TABLE_WRITE_PROPERTIES"
	CATALOGPRIVILEGE_VIEW_WRITE_PROPERTIES        CatalogPrivilege = "VIEW_WRITE_PROPERTIES"
	CATALOGPRIVILEGE_TABLE_READ_DATA              CatalogPrivilege = "TABLE_READ_DATA"
	CATALOGPRIVILEGE_TABLE_WRITE_DATA             CatalogPrivilege = "TABLE_WRITE_DATA"
	CATALOGPRIVILEGE_NAMESPACE_FULL_METADATA      CatalogPrivilege = "NAMESPACE_FULL_METADATA"
	CATALOGPRIVILEGE_TABLE_FULL_METADATA          CatalogPrivilege = "TABLE_FULL_METADATA"
	CATALOGPRIVILEGE_VIEW_FULL_METADATA           CatalogPrivilege = "VIEW_FULL_METADATA"
	CATALOGPRIVILEGE_POLICY_CREATE                CatalogPrivilege = "POLICY_CREATE"
	CATALOGPRIVILEGE_POLICY_WRITE                 CatalogPrivilege = "POLICY_WRITE"
	CATALOGPRIVILEGE_POLICY_READ                  CatalogPrivilege = "POLICY_READ"
	CATALOGPRIVILEGE_POLICY_DROP                  CatalogPrivilege = "POLICY_DROP"
	CATALOGPRIVILEGE_POLICY_LIST                  CatalogPrivilege = "POLICY_LIST"
	CATALOGPRIVILEGE_POLICY_FULL_METADATA         CatalogPrivilege = "POLICY_FULL_METADATA"
	CATALOGPRIVILEGE_CATALOG_ATTACH_POLICY        CatalogPrivilege = "CATALOG_ATTACH_POLICY"
	CATALOGPRIVILEGE_CATALOG_DETACH_POLICY        CatalogPrivilege = "CATALOG_DETACH_POLICY"
	CATALOGPRIVILEGE_TABLE_ASSIGN_UUID            CatalogPrivilege = "TABLE_ASSIGN_UUID"
	CATALOGPRIVILEGE_TABLE_UPGRADE_FORMAT_VERSION CatalogPrivilege = "TABLE_UPGRADE_FORMAT_VERSION"
	CATALOGPRIVILEGE_TABLE_ADD_SCHEMA             CatalogPrivilege = "TABLE_ADD_SCHEMA"
	CATALOGPRIVILEGE_TABLE_SET_CURRENT_SCHEMA     CatalogPrivilege = "TABLE_SET_CURRENT_SCHEMA"
	CATALOGPRIVILEGE_TABLE_ADD_PARTITION_SPEC     CatalogPrivilege = "TABLE_ADD_PARTITION_SPEC"
	CATALOGPRIVILEGE_TABLE_ADD_SORT_ORDER         CatalogPrivilege = "TABLE_ADD_SORT_ORDER"
	CATALOGPRIVILEGE_TABLE_SET_DEFAULT_SORT_ORDER CatalogPrivilege = "TABLE_SET_DEFAULT_SORT_ORDER"
	CATALOGPRIVILEGE_TABLE_ADD_SNAPSHOT           CatalogPrivilege = "TABLE_ADD_SNAPSHOT"
	CATALOGPRIVILEGE_TABLE_SET_SNAPSHOT_REF       CatalogPrivilege = "TABLE_SET_SNAPSHOT_REF"
	CATALOGPRIVILEGE_TABLE_REMOVE_SNAPSHOTS       CatalogPrivilege = "TABLE_REMOVE_SNAPSHOTS"
	CATALOGPRIVILEGE_TABLE_REMOVE_SNAPSHOT_REF    CatalogPrivilege = "TABLE_REMOVE_SNAPSHOT_REF"
	CATALOGPRIVILEGE_TABLE_SET_LOCATION           CatalogPrivilege = "TABLE_SET_LOCATION"
	CATALOGPRIVILEGE_TABLE_SET_PROPERTIES         CatalogPrivilege = "TABLE_SET_PROPERTIES"
	CATALOGPRIVILEGE_TABLE_REMOVE_PROPERTIES      CatalogPrivilege = "TABLE_REMOVE_PROPERTIES"
	CATALOGPRIVILEGE_TABLE_SET_STATISTICS         CatalogPrivilege = "TABLE_SET_STATISTICS"
	CATALOGPRIVILEGE_TABLE_REMOVE_STATISTICS      CatalogPrivilege = "TABLE_REMOVE_STATISTICS"
	CATALOGPRIVILEGE_TABLE_REMOVE_PARTITION_SPECS CatalogPrivilege = "TABLE_REMOVE_PARTITION_SPECS"
	CATALOGPRIVILEGE_TABLE_MANAGE_STRUCTURE       CatalogPrivilege = "TABLE_MANAGE_STRUCTURE"
)

// All allowed values of CatalogPrivilege enum
var AllowedCatalogPrivilegeEnumValues = []CatalogPrivilege{
	"CATALOG_MANAGE_ACCESS",
	"CATALOG_MANAGE_CONTENT",
	"CATALOG_MANAGE_METADATA",
	"CATALOG_READ_PROPERTIES",
	"CATALOG_WRITE_PROPERTIES",
	"NAMESPACE_CREATE",
	"TABLE_CREATE",
	"VIEW_CREATE",
	"NAMESPACE_DROP",
	"TABLE_DROP",
	"VIEW_DROP",
	"NAMESPACE_LIST",
	"TABLE_LIST",
	"VIEW_LIST",
	"NAMESPACE_READ_PROPERTIES",
	"TABLE_READ_PROPERTIES",
	"VIEW_READ_PROPERTIES",
	"NAMESPACE_WRITE_PROPERTIES",
	"TABLE_WRITE_PROPERTIES",
	"VIEW_WRITE_PROPERTIES",
	"TABLE_READ_DATA",
	"TABLE_WRITE_DATA",
	"NAMESPACE_FULL_METADATA",
	"TABLE_FULL_METADATA",
	"VIEW_FULL_METADATA",
	"POLICY_CREATE",
	"POLICY_WRITE",
	"POLICY_READ",
	"POLICY_DROP",
	"POLICY_LIST",
	"POLICY_FULL_METADATA",
	"CATALOG_ATTACH_POLICY",
	"CATALOG_DETACH_POLICY",
	"TABLE_ASSIGN_UUID",
	"TABLE_UPGRADE_FORMAT_VERSION",
	"TABLE_ADD_SCHEMA",
	"TABLE_SET_CURRENT_SCHEMA",
	"TABLE_ADD_PARTITION_SPEC",
	"TABLE_ADD_SORT_ORDER",
	"TABLE_SET_DEFAULT_SORT_ORDER",
	"TABLE_ADD_SNAPSHOT",
	"TABLE_SET_SNAPSHOT_REF",
	"TABLE_REMOVE_SNAPSHOTS",
	"TABLE_REMOVE_SNAPSHOT_REF",
	"TABLE_SET_LOCATION",
	"TABLE_SET_PROPERTIES",
	"TABLE_REMOVE_PROPERTIES",
	"TABLE_SET_STATISTICS",
	"TABLE_REMOVE_STATISTICS",
	"TABLE_REMOVE_PARTITION_SPECS",
	"TABLE_MANAGE_STRUCTURE",
}

func (v *CatalogPrivilege) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CatalogPrivilege(value)
	for _, existing := range AllowedCatalogPrivilegeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CatalogPrivilege", value)
}

// NewCatalogPrivilegeFromValue returns a pointer to a valid CatalogPrivilege
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCatalogPrivilegeFromValue(v string) (*CatalogPrivilege, error) {
	ev := CatalogPrivilege(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CatalogPrivilege: valid values are %v", v, AllowedCatalogPrivilegeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CatalogPrivilege) IsValid() bool {
	for _, existing := range AllowedCatalogPrivilegeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CatalogPrivilege value
func (v CatalogPrivilege) Ptr() *CatalogPrivilege {
	return &v
}

type NullableCatalogPrivilege struct {
	value *CatalogPrivilege
	isSet bool
}

func (v NullableCatalogPrivilege) Get() *CatalogPrivilege {
	return v.value
}

func (v *NullableCatalogPrivilege) Set(val *CatalogPrivilege) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogPrivilege) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogPrivilege) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogPrivilege(val *CatalogPrivilege) *NullableCatalogPrivilege {
	return &NullableCatalogPrivilege{value: val, isSet: true}
}

func (v NullableCatalogPrivilege) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogPrivilege) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
