/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// NamespacePrivilege the model 'NamespacePrivilege'
type NamespacePrivilege string

// List of NamespacePrivilege
const (
	NAMESPACEPRIVILEGE_CATALOG_MANAGE_ACCESS        NamespacePrivilege = "CATALOG_MANAGE_ACCESS"
	NAMESPACEPRIVILEGE_CATALOG_MANAGE_CONTENT       NamespacePrivilege = "CATALOG_MANAGE_CONTENT"
	NAMESPACEPRIVILEGE_CATALOG_MANAGE_METADATA      NamespacePrivilege = "CATALOG_MANAGE_METADATA"
	NAMESPACEPRIVILEGE_NAMESPACE_CREATE             NamespacePrivilege = "NAMESPACE_CREATE"
	NAMESPACEPRIVILEGE_TABLE_CREATE                 NamespacePrivilege = "TABLE_CREATE"
	NAMESPACEPRIVILEGE_VIEW_CREATE                  NamespacePrivilege = "VIEW_CREATE"
	NAMESPACEPRIVILEGE_NAMESPACE_DROP               NamespacePrivilege = "NAMESPACE_DROP"
	NAMESPACEPRIVILEGE_TABLE_DROP                   NamespacePrivilege = "TABLE_DROP"
	NAMESPACEPRIVILEGE_VIEW_DROP                    NamespacePrivilege = "VIEW_DROP"
	NAMESPACEPRIVILEGE_NAMESPACE_LIST               NamespacePrivilege = "NAMESPACE_LIST"
	NAMESPACEPRIVILEGE_TABLE_LIST                   NamespacePrivilege = "TABLE_LIST"
	NAMESPACEPRIVILEGE_VIEW_LIST                    NamespacePrivilege = "VIEW_LIST"
	NAMESPACEPRIVILEGE_NAMESPACE_READ_PROPERTIES    NamespacePrivilege = "NAMESPACE_READ_PROPERTIES"
	NAMESPACEPRIVILEGE_TABLE_READ_PROPERTIES        NamespacePrivilege = "TABLE_READ_PROPERTIES"
	NAMESPACEPRIVILEGE_VIEW_READ_PROPERTIES         NamespacePrivilege = "VIEW_READ_PROPERTIES"
	NAMESPACEPRIVILEGE_NAMESPACE_WRITE_PROPERTIES   NamespacePrivilege = "NAMESPACE_WRITE_PROPERTIES"
	NAMESPACEPRIVILEGE_TABLE_WRITE_PROPERTIES       NamespacePrivilege = "TABLE_WRITE_PROPERTIES"
	NAMESPACEPRIVILEGE_VIEW_WRITE_PROPERTIES        NamespacePrivilege = "VIEW_WRITE_PROPERTIES"
	NAMESPACEPRIVILEGE_TABLE_READ_DATA              NamespacePrivilege = "TABLE_READ_DATA"
	NAMESPACEPRIVILEGE_TABLE_WRITE_DATA             NamespacePrivilege = "TABLE_WRITE_DATA"
	NAMESPACEPRIVILEGE_NAMESPACE_FULL_METADATA      NamespacePrivilege = "NAMESPACE_FULL_METADATA"
	NAMESPACEPRIVILEGE_TABLE_FULL_METADATA          NamespacePrivilege = "TABLE_FULL_METADATA"
	NAMESPACEPRIVILEGE_VIEW_FULL_METADATA           NamespacePrivilege = "VIEW_FULL_METADATA"
	NAMESPACEPRIVILEGE_POLICY_CREATE                NamespacePrivilege = "POLICY_CREATE"
	NAMESPACEPRIVILEGE_POLICY_WRITE                 NamespacePrivilege = "POLICY_WRITE"
	NAMESPACEPRIVILEGE_POLICY_READ                  NamespacePrivilege = "POLICY_READ"
	NAMESPACEPRIVILEGE_POLICY_DROP                  NamespacePrivilege = "POLICY_DROP"
	NAMESPACEPRIVILEGE_POLICY_LIST                  NamespacePrivilege = "POLICY_LIST"
	NAMESPACEPRIVILEGE_POLICY_FULL_METADATA         NamespacePrivilege = "POLICY_FULL_METADATA"
	NAMESPACEPRIVILEGE_NAMESPACE_ATTACH_POLICY      NamespacePrivilege = "NAMESPACE_ATTACH_POLICY"
	NAMESPACEPRIVILEGE_NAMESPACE_DETACH_POLICY      NamespacePrivilege = "NAMESPACE_DETACH_POLICY"
	NAMESPACEPRIVILEGE_TABLE_ASSIGN_UUID            NamespacePrivilege = "TABLE_ASSIGN_UUID"
	NAMESPACEPRIVILEGE_TABLE_UPGRADE_FORMAT_VERSION NamespacePrivilege = "TABLE_UPGRADE_FORMAT_VERSION"
	NAMESPACEPRIVILEGE_TABLE_ADD_SCHEMA             NamespacePrivilege = "TABLE_ADD_SCHEMA"
	NAMESPACEPRIVILEGE_TABLE_SET_CURRENT_SCHEMA     NamespacePrivilege = "TABLE_SET_CURRENT_SCHEMA"
	NAMESPACEPRIVILEGE_TABLE_ADD_PARTITION_SPEC     NamespacePrivilege = "TABLE_ADD_PARTITION_SPEC"
	NAMESPACEPRIVILEGE_TABLE_ADD_SORT_ORDER         NamespacePrivilege = "TABLE_ADD_SORT_ORDER"
	NAMESPACEPRIVILEGE_TABLE_SET_DEFAULT_SORT_ORDER NamespacePrivilege = "TABLE_SET_DEFAULT_SORT_ORDER"
	NAMESPACEPRIVILEGE_TABLE_ADD_SNAPSHOT           NamespacePrivilege = "TABLE_ADD_SNAPSHOT"
	NAMESPACEPRIVILEGE_TABLE_SET_SNAPSHOT_REF       NamespacePrivilege = "TABLE_SET_SNAPSHOT_REF"
	NAMESPACEPRIVILEGE_TABLE_REMOVE_SNAPSHOTS       NamespacePrivilege = "TABLE_REMOVE_SNAPSHOTS"
	NAMESPACEPRIVILEGE_TABLE_REMOVE_SNAPSHOT_REF    NamespacePrivilege = "TABLE_REMOVE_SNAPSHOT_REF"
	NAMESPACEPRIVILEGE_TABLE_SET_LOCATION           NamespacePrivilege = "TABLE_SET_LOCATION"
	NAMESPACEPRIVILEGE_TABLE_SET_PROPERTIES         NamespacePrivilege = "TABLE_SET_PROPERTIES"
	NAMESPACEPRIVILEGE_TABLE_REMOVE_PROPERTIES      NamespacePrivilege = "TABLE_REMOVE_PROPERTIES"
	NAMESPACEPRIVILEGE_TABLE_SET_STATISTICS         NamespacePrivilege = "TABLE_SET_STATISTICS"
	NAMESPACEPRIVILEGE_TABLE_REMOVE_STATISTICS      NamespacePrivilege = "TABLE_REMOVE_STATISTICS"
	NAMESPACEPRIVILEGE_TABLE_REMOVE_PARTITION_SPECS NamespacePrivilege = "TABLE_REMOVE_PARTITION_SPECS"
	NAMESPACEPRIVILEGE_TABLE_MANAGE_STRUCTURE       NamespacePrivilege = "TABLE_MANAGE_STRUCTURE"
)

// All allowed values of NamespacePrivilege enum
var AllowedNamespacePrivilegeEnumValues = []NamespacePrivilege{
	"CATALOG_MANAGE_ACCESS",
	"CATALOG_MANAGE_CONTENT",
	"CATALOG_MANAGE_METADATA",
	"NAMESPACE_CREATE",
	"TABLE_CREATE",
	"VIEW_CREATE",
	"NAMESPACE_DROP",
	"TABLE_DROP",
	"VIEW_DROP",
	"NAMESPACE_LIST",
	"TABLE_LIST",
	"VIEW_LIST",
	"NAMESPACE_READ_PROPERTIES",
	"TABLE_READ_PROPERTIES",
	"VIEW_READ_PROPERTIES",
	"NAMESPACE_WRITE_PROPERTIES",
	"TABLE_WRITE_PROPERTIES",
	"VIEW_WRITE_PROPERTIES",
	"TABLE_READ_DATA",
	"TABLE_WRITE_DATA",
	"NAMESPACE_FULL_METADATA",
	"TABLE_FULL_METADATA",
	"VIEW_FULL_METADATA",
	"POLICY_CREATE",
	"POLICY_WRITE",
	"POLICY_READ",
	"POLICY_DROP",
	"POLICY_LIST",
	"POLICY_FULL_METADATA",
	"NAMESPACE_ATTACH_POLICY",
	"NAMESPACE_DETACH_POLICY",
	"TABLE_ASSIGN_UUID",
	"TABLE_UPGRADE_FORMAT_VERSION",
	"TABLE_ADD_SCHEMA",
	"TABLE_SET_CURRENT_SCHEMA",
	"TABLE_ADD_PARTITION_SPEC",
	"TABLE_ADD_SORT_ORDER",
	"TABLE_SET_DEFAULT_SORT_ORDER",
	"TABLE_ADD_SNAPSHOT",
	"TABLE_SET_SNAPSHOT_REF",
	"TABLE_REMOVE_SNAPSHOTS",
	"TABLE_REMOVE_SNAPSHOT_REF",
	"TABLE_SET_LOCATION",
	"TABLE_SET_PROPERTIES",
	"TABLE_REMOVE_PROPERTIES",
	"TABLE_SET_STATISTICS",
	"TABLE_REMOVE_STATISTICS",
	"TABLE_REMOVE_PARTITION_SPECS",
	"TABLE_MANAGE_STRUCTURE",
}

func (v *NamespacePrivilege) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NamespacePrivilege(value)
	for _, existing := range AllowedNamespacePrivilegeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NamespacePrivilege", value)
}

// NewNamespacePrivilegeFromValue returns a pointer to a valid NamespacePrivilege
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNamespacePrivilegeFromValue(v string) (*NamespacePrivilege, error) {
	ev := NamespacePrivilege(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NamespacePrivilege: valid values are %v", v, AllowedNamespacePrivilegeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NamespacePrivilege) IsValid() bool {
	for _, existing := range AllowedNamespacePrivilegeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NamespacePrivilege value
func (v NamespacePrivilege) Ptr() *NamespacePrivilege {
	return &v
}

type NullableNamespacePrivilege struct {
	value *NamespacePrivilege
	isSet bool
}

func (v NullableNamespacePrivilege) Get() *NamespacePrivilege {
	return v.value
}

func (v *NullableNamespacePrivilege) Set(val *NamespacePrivilege) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespacePrivilege) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespacePrivilege) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespacePrivilege(val *NamespacePrivilege) *NullableNamespacePrivilege {
	return &NullableNamespacePrivilege{value: val, isSet: true}
}

func (v NullableNamespacePrivilege) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespacePrivilege) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
