/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the CatalogRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogRole{}

// CatalogRole struct for CatalogRole
type CatalogRole struct {
	// The name of the role
	Name string `json:"name" validate:"regexp=^(?!\\\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\\\$).*$"`
	Properties *map[string]string `json:"properties,omitempty"`
	CreateTimestamp *int64 `json:"createTimestamp,omitempty"`
	LastUpdateTimestamp *int64 `json:"lastUpdateTimestamp,omitempty"`
	// The version of the catalog role object used to determine if the catalog role metadata has changed
	EntityVersion *int32 `json:"entityVersion,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CatalogRole CatalogRole

// NewCatalogRole instantiates a new CatalogRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogRole(name string) *CatalogRole {
	this := CatalogRole{}
	this.Name = name
	return &this
}

// NewCatalogRoleWithDefaults instantiates a new CatalogRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogRoleWithDefaults() *CatalogRole {
	this := CatalogRole{}
	return &this
}

// GetName returns the Name field value
func (o *CatalogRole) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CatalogRole) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CatalogRole) SetName(v string) {
	o.Name = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *CatalogRole) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogRole) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *CatalogRole) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *CatalogRole) SetProperties(v map[string]string) {
	o.Properties = &v
}

// GetCreateTimestamp returns the CreateTimestamp field value if set, zero value otherwise.
func (o *CatalogRole) GetCreateTimestamp() int64 {
	if o == nil || IsNil(o.CreateTimestamp) {
		var ret int64
		return ret
	}
	return *o.CreateTimestamp
}

// GetCreateTimestampOk returns a tuple with the CreateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogRole) GetCreateTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.CreateTimestamp) {
		return nil, false
	}
	return o.CreateTimestamp, true
}

// HasCreateTimestamp returns a boolean if a field has been set.
func (o *CatalogRole) HasCreateTimestamp() bool {
	if o != nil && !IsNil(o.CreateTimestamp) {
		return true
	}

	return false
}

// SetCreateTimestamp gets a reference to the given int64 and assigns it to the CreateTimestamp field.
func (o *CatalogRole) SetCreateTimestamp(v int64) {
	o.CreateTimestamp = &v
}

// GetLastUpdateTimestamp returns the LastUpdateTimestamp field value if set, zero value otherwise.
func (o *CatalogRole) GetLastUpdateTimestamp() int64 {
	if o == nil || IsNil(o.LastUpdateTimestamp) {
		var ret int64
		return ret
	}
	return *o.LastUpdateTimestamp
}

// GetLastUpdateTimestampOk returns a tuple with the LastUpdateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogRole) GetLastUpdateTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdateTimestamp) {
		return nil, false
	}
	return o.LastUpdateTimestamp, true
}

// HasLastUpdateTimestamp returns a boolean if a field has been set.
func (o *CatalogRole) HasLastUpdateTimestamp() bool {
	if o != nil && !IsNil(o.LastUpdateTimestamp) {
		return true
	}

	return false
}

// SetLastUpdateTimestamp gets a reference to the given int64 and assigns it to the LastUpdateTimestamp field.
func (o *CatalogRole) SetLastUpdateTimestamp(v int64) {
	o.LastUpdateTimestamp = &v
}

// GetEntityVersion returns the EntityVersion field value if set, zero value otherwise.
func (o *CatalogRole) GetEntityVersion() int32 {
	if o == nil || IsNil(o.EntityVersion) {
		var ret int32
		return ret
	}
	return *o.EntityVersion
}

// GetEntityVersionOk returns a tuple with the EntityVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogRole) GetEntityVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.EntityVersion) {
		return nil, false
	}
	return o.EntityVersion, true
}

// HasEntityVersion returns a boolean if a field has been set.
func (o *CatalogRole) HasEntityVersion() bool {
	if o != nil && !IsNil(o.EntityVersion) {
		return true
	}

	return false
}

// SetEntityVersion gets a reference to the given int32 and assigns it to the EntityVersion field.
func (o *CatalogRole) SetEntityVersion(v int32) {
	o.EntityVersion = &v
}

func (o CatalogRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.CreateTimestamp) {
		toSerialize["createTimestamp"] = o.CreateTimestamp
	}
	if !IsNil(o.LastUpdateTimestamp) {
		toSerialize["lastUpdateTimestamp"] = o.LastUpdateTimestamp
	}
	if !IsNil(o.EntityVersion) {
		toSerialize["entityVersion"] = o.EntityVersion
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CatalogRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogRole := _CatalogRole{}

	err = json.Unmarshal(data, &varCatalogRole)

	if err != nil {
		return err
	}

	*o = CatalogRole(varCatalogRole)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "properties")
		delete(additionalProperties, "createTimestamp")
		delete(additionalProperties, "lastUpdateTimestamp")
		delete(additionalProperties, "entityVersion")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCatalogRole struct {
	value *CatalogRole
	isSet bool
}

func (v NullableCatalogRole) Get() *CatalogRole {
	return v.value
}

func (v *NullableCatalogRole) Set(val *CatalogRole) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogRole) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogRole(val *CatalogRole) *NullableCatalogRole {
	return &NullableCatalogRole{value: val, isSet: true}
}

func (v NullableCatalogRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


