/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the AddGrantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddGrantRequest{}

// AddGrantRequest struct for AddGrantRequest
type AddGrantRequest struct {
	Grant                *GrantResource `json:"grant,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddGrantRequest AddGrantRequest

// NewAddGrantRequest instantiates a new AddGrantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddGrantRequest() *AddGrantRequest {
	this := AddGrantRequest{}
	return &this
}

// NewAddGrantRequestWithDefaults instantiates a new AddGrantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddGrantRequestWithDefaults() *AddGrantRequest {
	this := AddGrantRequest{}
	return &this
}

// GetGrant returns the Grant field value if set, zero value otherwise.
func (o *AddGrantRequest) GetGrant() GrantResource {
	if o == nil || IsNil(o.Grant) {
		var ret GrantResource
		return ret
	}
	return *o.Grant
}

// GetGrantOk returns a tuple with the Grant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddGrantRequest) GetGrantOk() (*GrantResource, bool) {
	if o == nil || IsNil(o.Grant) {
		return nil, false
	}
	return o.Grant, true
}

// HasGrant returns a boolean if a field has been set.
func (o *AddGrantRequest) HasGrant() bool {
	if o != nil && !IsNil(o.Grant) {
		return true
	}

	return false
}

// SetGrant gets a reference to the given GrantResource and assigns it to the Grant field.
func (o *AddGrantRequest) SetGrant(v GrantResource) {
	o.Grant = &v
}

func (o AddGrantRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddGrantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Grant) {
		toSerialize["grant"] = o.Grant
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddGrantRequest) UnmarshalJSON(data []byte) (err error) {
	varAddGrantRequest := _AddGrantRequest{}

	err = json.Unmarshal(data, &varAddGrantRequest)

	if err != nil {
		return err
	}

	*o = AddGrantRequest(varAddGrantRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "grant")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddGrantRequest struct {
	value *AddGrantRequest
	isSet bool
}

func (v NullableAddGrantRequest) Get() *AddGrantRequest {
	return v.value
}

func (v *NullableAddGrantRequest) Set(val *AddGrantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddGrantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddGrantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddGrantRequest(val *AddGrantRequest) *NullableAddGrantRequest {
	return &NullableAddGrantRequest{value: val, isSet: true}
}

func (v NullableAddGrantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddGrantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
