/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the ResetPrincipalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetPrincipalRequest{}

// ResetPrincipalRequest struct for ResetPrincipalRequest
type ResetPrincipalRequest struct {
	// Optional client ID to set for the principal. Must be a valid client ID previously generated by this service. 
	ClientId *string `json:"clientId,omitempty"`
	// Optional client secret to set for the principal. Polaris service implementations may impose extra requirements on what is accepted as a secret (special chars, length, etc.) 
	ClientSecret *string `json:"clientSecret,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ResetPrincipalRequest ResetPrincipalRequest

// NewResetPrincipalRequest instantiates a new ResetPrincipalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetPrincipalRequest() *ResetPrincipalRequest {
	this := ResetPrincipalRequest{}
	return &this
}

// NewResetPrincipalRequestWithDefaults instantiates a new ResetPrincipalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetPrincipalRequestWithDefaults() *ResetPrincipalRequest {
	this := ResetPrincipalRequest{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *ResetPrincipalRequest) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResetPrincipalRequest) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *ResetPrincipalRequest) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *ResetPrincipalRequest) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *ResetPrincipalRequest) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResetPrincipalRequest) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *ResetPrincipalRequest) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *ResetPrincipalRequest) SetClientSecret(v string) {
	o.ClientSecret = &v
}

func (o ResetPrincipalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResetPrincipalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResetPrincipalRequest) UnmarshalJSON(data []byte) (err error) {
	varResetPrincipalRequest := _ResetPrincipalRequest{}

	err = json.Unmarshal(data, &varResetPrincipalRequest)

	if err != nil {
		return err
	}

	*o = ResetPrincipalRequest(varResetPrincipalRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "clientId")
		delete(additionalProperties, "clientSecret")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResetPrincipalRequest struct {
	value *ResetPrincipalRequest
	isSet bool
}

func (v NullableResetPrincipalRequest) Get() *ResetPrincipalRequest {
	return v.value
}

func (v *NullableResetPrincipalRequest) Set(val *ResetPrincipalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResetPrincipalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResetPrincipalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetPrincipalRequest(val *ResetPrincipalRequest) *NullableResetPrincipalRequest {
	return &NullableResetPrincipalRequest{value: val, isSet: true}
}

func (v NullableResetPrincipalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetPrincipalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


