/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the GrantPrincipalRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantPrincipalRoleRequest{}

// GrantPrincipalRoleRequest struct for GrantPrincipalRoleRequest
type GrantPrincipalRoleRequest struct {
	PrincipalRole        *PrincipalRole `json:"principalRole,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GrantPrincipalRoleRequest GrantPrincipalRoleRequest

// NewGrantPrincipalRoleRequest instantiates a new GrantPrincipalRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantPrincipalRoleRequest() *GrantPrincipalRoleRequest {
	this := GrantPrincipalRoleRequest{}
	return &this
}

// NewGrantPrincipalRoleRequestWithDefaults instantiates a new GrantPrincipalRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantPrincipalRoleRequestWithDefaults() *GrantPrincipalRoleRequest {
	this := GrantPrincipalRoleRequest{}
	return &this
}

// GetPrincipalRole returns the PrincipalRole field value if set, zero value otherwise.
func (o *GrantPrincipalRoleRequest) GetPrincipalRole() PrincipalRole {
	if o == nil || IsNil(o.PrincipalRole) {
		var ret PrincipalRole
		return ret
	}
	return *o.PrincipalRole
}

// GetPrincipalRoleOk returns a tuple with the PrincipalRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GrantPrincipalRoleRequest) GetPrincipalRoleOk() (*PrincipalRole, bool) {
	if o == nil || IsNil(o.PrincipalRole) {
		return nil, false
	}
	return o.PrincipalRole, true
}

// HasPrincipalRole returns a boolean if a field has been set.
func (o *GrantPrincipalRoleRequest) HasPrincipalRole() bool {
	if o != nil && !IsNil(o.PrincipalRole) {
		return true
	}

	return false
}

// SetPrincipalRole gets a reference to the given PrincipalRole and assigns it to the PrincipalRole field.
func (o *GrantPrincipalRoleRequest) SetPrincipalRole(v PrincipalRole) {
	o.PrincipalRole = &v
}

func (o GrantPrincipalRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantPrincipalRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrincipalRole) {
		toSerialize["principalRole"] = o.PrincipalRole
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GrantPrincipalRoleRequest) UnmarshalJSON(data []byte) (err error) {
	varGrantPrincipalRoleRequest := _GrantPrincipalRoleRequest{}

	err = json.Unmarshal(data, &varGrantPrincipalRoleRequest)

	if err != nil {
		return err
	}

	*o = GrantPrincipalRoleRequest(varGrantPrincipalRoleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "principalRole")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGrantPrincipalRoleRequest struct {
	value *GrantPrincipalRoleRequest
	isSet bool
}

func (v NullableGrantPrincipalRoleRequest) Get() *GrantPrincipalRoleRequest {
	return v.value
}

func (v *NullableGrantPrincipalRoleRequest) Set(val *GrantPrincipalRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantPrincipalRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantPrincipalRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantPrincipalRoleRequest(val *GrantPrincipalRoleRequest) *NullableGrantPrincipalRoleRequest {
	return &NullableGrantPrincipalRoleRequest{value: val, isSet: true}
}

func (v NullableGrantPrincipalRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantPrincipalRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
