/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the GcpStorageConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GcpStorageConfigInfo{}

// GcpStorageConfigInfo gcp storage configuration info
type GcpStorageConfigInfo struct {
	StorageConfigInfo
	// a Google cloud storage service account
	GcsServiceAccount    *string `json:"gcsServiceAccount,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GcpStorageConfigInfo GcpStorageConfigInfo

// NewGcpStorageConfigInfo instantiates a new GcpStorageConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGcpStorageConfigInfo(storageType string) *GcpStorageConfigInfo {
	this := GcpStorageConfigInfo{}
	this.StorageType = storageType
	return &this
}

// NewGcpStorageConfigInfoWithDefaults instantiates a new GcpStorageConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGcpStorageConfigInfoWithDefaults() *GcpStorageConfigInfo {
	this := GcpStorageConfigInfo{}
	return &this
}

// GetGcsServiceAccount returns the GcsServiceAccount field value if set, zero value otherwise.
func (o *GcpStorageConfigInfo) GetGcsServiceAccount() string {
	if o == nil || IsNil(o.GcsServiceAccount) {
		var ret string
		return ret
	}
	return *o.GcsServiceAccount
}

// GetGcsServiceAccountOk returns a tuple with the GcsServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GcpStorageConfigInfo) GetGcsServiceAccountOk() (*string, bool) {
	if o == nil || IsNil(o.GcsServiceAccount) {
		return nil, false
	}
	return o.GcsServiceAccount, true
}

// HasGcsServiceAccount returns a boolean if a field has been set.
func (o *GcpStorageConfigInfo) HasGcsServiceAccount() bool {
	if o != nil && !IsNil(o.GcsServiceAccount) {
		return true
	}

	return false
}

// SetGcsServiceAccount gets a reference to the given string and assigns it to the GcsServiceAccount field.
func (o *GcpStorageConfigInfo) SetGcsServiceAccount(v string) {
	o.GcsServiceAccount = &v
}

func (o GcpStorageConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GcpStorageConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GcsServiceAccount) {
		toSerialize["gcsServiceAccount"] = o.GcsServiceAccount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GcpStorageConfigInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"storageType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGcpStorageConfigInfo := _GcpStorageConfigInfo{}

	err = json.Unmarshal(data, &varGcpStorageConfigInfo)

	if err != nil {
		return err
	}

	*o = GcpStorageConfigInfo(varGcpStorageConfigInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "gcsServiceAccount")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGcpStorageConfigInfo struct {
	value *GcpStorageConfigInfo
	isSet bool
}

func (v NullableGcpStorageConfigInfo) Get() *GcpStorageConfigInfo {
	return v.value
}

func (v *NullableGcpStorageConfigInfo) Set(val *GcpStorageConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGcpStorageConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGcpStorageConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcpStorageConfigInfo(val *GcpStorageConfigInfo) *NullableGcpStorageConfigInfo {
	return &NullableGcpStorageConfigInfo{value: val, isSet: true}
}

func (v NullableGcpStorageConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcpStorageConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
