/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the IcebergRestConnectionConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IcebergRestConnectionConfigInfo{}

// IcebergRestConnectionConfigInfo struct for IcebergRestConnectionConfigInfo
type IcebergRestConnectionConfigInfo struct {
	ConnectionConfigInfo
	// The name of a remote catalog instance within the remote catalog service; in some older systems this is specified as the 'warehouse' when multiple logical catalogs are served under the same base uri, and often translates into a 'prefix' added to all REST resource paths
	RemoteCatalogName    *string `json:"remoteCatalogName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IcebergRestConnectionConfigInfo IcebergRestConnectionConfigInfo

// NewIcebergRestConnectionConfigInfo instantiates a new IcebergRestConnectionConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIcebergRestConnectionConfigInfo(connectionType string) *IcebergRestConnectionConfigInfo {
	this := IcebergRestConnectionConfigInfo{}
	this.ConnectionType = connectionType
	return &this
}

// NewIcebergRestConnectionConfigInfoWithDefaults instantiates a new IcebergRestConnectionConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIcebergRestConnectionConfigInfoWithDefaults() *IcebergRestConnectionConfigInfo {
	this := IcebergRestConnectionConfigInfo{}
	return &this
}

// GetRemoteCatalogName returns the RemoteCatalogName field value if set, zero value otherwise.
func (o *IcebergRestConnectionConfigInfo) GetRemoteCatalogName() string {
	if o == nil || IsNil(o.RemoteCatalogName) {
		var ret string
		return ret
	}
	return *o.RemoteCatalogName
}

// GetRemoteCatalogNameOk returns a tuple with the RemoteCatalogName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IcebergRestConnectionConfigInfo) GetRemoteCatalogNameOk() (*string, bool) {
	if o == nil || IsNil(o.RemoteCatalogName) {
		return nil, false
	}
	return o.RemoteCatalogName, true
}

// HasRemoteCatalogName returns a boolean if a field has been set.
func (o *IcebergRestConnectionConfigInfo) HasRemoteCatalogName() bool {
	if o != nil && !IsNil(o.RemoteCatalogName) {
		return true
	}

	return false
}

// SetRemoteCatalogName gets a reference to the given string and assigns it to the RemoteCatalogName field.
func (o *IcebergRestConnectionConfigInfo) SetRemoteCatalogName(v string) {
	o.RemoteCatalogName = &v
}

func (o IcebergRestConnectionConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IcebergRestConnectionConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RemoteCatalogName) {
		toSerialize["remoteCatalogName"] = o.RemoteCatalogName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IcebergRestConnectionConfigInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectionType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIcebergRestConnectionConfigInfo := _IcebergRestConnectionConfigInfo{}

	err = json.Unmarshal(data, &varIcebergRestConnectionConfigInfo)

	if err != nil {
		return err
	}

	*o = IcebergRestConnectionConfigInfo(varIcebergRestConnectionConfigInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "remoteCatalogName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIcebergRestConnectionConfigInfo struct {
	value *IcebergRestConnectionConfigInfo
	isSet bool
}

func (v NullableIcebergRestConnectionConfigInfo) Get() *IcebergRestConnectionConfigInfo {
	return v.value
}

func (v *NullableIcebergRestConnectionConfigInfo) Set(val *IcebergRestConnectionConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableIcebergRestConnectionConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableIcebergRestConnectionConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIcebergRestConnectionConfigInfo(val *IcebergRestConnectionConfigInfo) *NullableIcebergRestConnectionConfigInfo {
	return &NullableIcebergRestConnectionConfigInfo{value: val, isSet: true}
}

func (v NullableIcebergRestConnectionConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIcebergRestConnectionConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
