/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdatePrincipalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePrincipalRequest{}

// UpdatePrincipalRequest Updates to apply to a Principal
type UpdatePrincipalRequest struct {
	// The version of the object onto which this update is applied; if the object changed, the update will fail and the caller should retry after fetching the latest version.
	CurrentEntityVersion int32             `json:"currentEntityVersion"`
	Properties           map[string]string `json:"properties"`
	AdditionalProperties map[string]interface{}
}

type _UpdatePrincipalRequest UpdatePrincipalRequest

// NewUpdatePrincipalRequest instantiates a new UpdatePrincipalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePrincipalRequest(currentEntityVersion int32, properties map[string]string) *UpdatePrincipalRequest {
	this := UpdatePrincipalRequest{}
	this.CurrentEntityVersion = currentEntityVersion
	this.Properties = properties
	return &this
}

// NewUpdatePrincipalRequestWithDefaults instantiates a new UpdatePrincipalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePrincipalRequestWithDefaults() *UpdatePrincipalRequest {
	this := UpdatePrincipalRequest{}
	return &this
}

// GetCurrentEntityVersion returns the CurrentEntityVersion field value
func (o *UpdatePrincipalRequest) GetCurrentEntityVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentEntityVersion
}

// GetCurrentEntityVersionOk returns a tuple with the CurrentEntityVersion field value
// and a boolean to check if the value has been set.
func (o *UpdatePrincipalRequest) GetCurrentEntityVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentEntityVersion, true
}

// SetCurrentEntityVersion sets field value
func (o *UpdatePrincipalRequest) SetCurrentEntityVersion(v int32) {
	o.CurrentEntityVersion = v
}

// GetProperties returns the Properties field value
func (o *UpdatePrincipalRequest) GetProperties() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *UpdatePrincipalRequest) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *UpdatePrincipalRequest) SetProperties(v map[string]string) {
	o.Properties = v
}

func (o UpdatePrincipalRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePrincipalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currentEntityVersion"] = o.CurrentEntityVersion
	toSerialize["properties"] = o.Properties

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdatePrincipalRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currentEntityVersion",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePrincipalRequest := _UpdatePrincipalRequest{}

	err = json.Unmarshal(data, &varUpdatePrincipalRequest)

	if err != nil {
		return err
	}

	*o = UpdatePrincipalRequest(varUpdatePrincipalRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "currentEntityVersion")
		delete(additionalProperties, "properties")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdatePrincipalRequest struct {
	value *UpdatePrincipalRequest
	isSet bool
}

func (v NullableUpdatePrincipalRequest) Get() *UpdatePrincipalRequest {
	return v.value
}

func (v *NullableUpdatePrincipalRequest) Set(val *UpdatePrincipalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePrincipalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePrincipalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePrincipalRequest(val *UpdatePrincipalRequest) *NullableUpdatePrincipalRequest {
	return &NullableUpdatePrincipalRequest{value: val, isSet: true}
}

func (v NullableUpdatePrincipalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePrincipalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
