/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the Principals type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Principals{}

// Principals A list of Principals
type Principals struct {
	Principals []Principal `json:"principals"`
	AdditionalProperties map[string]interface{}
}

type _Principals Principals

// NewPrincipals instantiates a new Principals object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipals(principals []Principal) *Principals {
	this := Principals{}
	this.Principals = principals
	return &this
}

// NewPrincipalsWithDefaults instantiates a new Principals object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalsWithDefaults() *Principals {
	this := Principals{}
	return &this
}

// GetPrincipals returns the Principals field value
func (o *Principals) GetPrincipals() []Principal {
	if o == nil {
		var ret []Principal
		return ret
	}

	return o.Principals
}

// GetPrincipalsOk returns a tuple with the Principals field value
// and a boolean to check if the value has been set.
func (o *Principals) GetPrincipalsOk() ([]Principal, bool) {
	if o == nil {
		return nil, false
	}
	return o.Principals, true
}

// SetPrincipals sets field value
func (o *Principals) SetPrincipals(v []Principal) {
	o.Principals = v
}

func (o Principals) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Principals) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["principals"] = o.Principals

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Principals) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"principals",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrincipals := _Principals{}

	err = json.Unmarshal(data, &varPrincipals)

	if err != nil {
		return err
	}

	*o = Principals(varPrincipals)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "principals")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrincipals struct {
	value *Principals
	isSet bool
}

func (v NullablePrincipals) Get() *Principals {
	return v.value
}

func (v *NullablePrincipals) Set(val *Principals) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipals) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipals) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipals(val *Principals) *NullablePrincipals {
	return &NullablePrincipals{value: val, isSet: true}
}

func (v NullablePrincipals) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipals) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


