/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// PolicyPrivilege the model 'PolicyPrivilege'
type PolicyPrivilege string

// List of PolicyPrivilege
const (
	POLICYPRIVILEGE_CATALOG_MANAGE_ACCESS PolicyPrivilege = "CATALOG_MANAGE_ACCESS"
	POLICYPRIVILEGE_POLICY_READ PolicyPrivilege = "POLICY_READ"
	POLICYPRIVILEGE_POLICY_DROP PolicyPrivilege = "POLICY_DROP"
	POLICYPRIVILEGE_POLICY_WRITE PolicyPrivilege = "POLICY_WRITE"
	POLICYPRIVILEGE_POLICY_LIST PolicyPrivilege = "POLICY_LIST"
	POLICYPRIVILEGE_POLICY_FULL_METADATA PolicyPrivilege = "POLICY_FULL_METADATA"
	POLICYPRIVILEGE_POLICY_ATTACH PolicyPrivilege = "POLICY_ATTACH"
	POLICYPRIVILEGE_POLICY_DETACH PolicyPrivilege = "POLICY_DETACH"
)

// All allowed values of PolicyPrivilege enum
var AllowedPolicyPrivilegeEnumValues = []PolicyPrivilege{
	"CATALOG_MANAGE_ACCESS",
	"POLICY_READ",
	"POLICY_DROP",
	"POLICY_WRITE",
	"POLICY_LIST",
	"POLICY_FULL_METADATA",
	"POLICY_ATTACH",
	"POLICY_DETACH",
}

func (v *PolicyPrivilege) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PolicyPrivilege(value)
	for _, existing := range AllowedPolicyPrivilegeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PolicyPrivilege", value)
}

// NewPolicyPrivilegeFromValue returns a pointer to a valid PolicyPrivilege
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPolicyPrivilegeFromValue(v string) (*PolicyPrivilege, error) {
	ev := PolicyPrivilege(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PolicyPrivilege: valid values are %v", v, AllowedPolicyPrivilegeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PolicyPrivilege) IsValid() bool {
	for _, existing := range AllowedPolicyPrivilegeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PolicyPrivilege value
func (v PolicyPrivilege) Ptr() *PolicyPrivilege {
	return &v
}

type NullablePolicyPrivilege struct {
	value *PolicyPrivilege
	isSet bool
}

func (v NullablePolicyPrivilege) Get() *PolicyPrivilege {
	return v.value
}

func (v *NullablePolicyPrivilege) Set(val *PolicyPrivilege) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyPrivilege) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyPrivilege) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyPrivilege(val *PolicyPrivilege) *NullablePolicyPrivilege {
	return &NullablePolicyPrivilege{value: val, isSet: true}
}

func (v NullablePolicyPrivilege) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyPrivilege) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

