/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the ViewGrant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewGrant{}

// ViewGrant struct for ViewGrant
type ViewGrant struct {
	GrantResource
	Namespace []string `json:"namespace"`
	ViewName string `json:"viewName"`
	Privilege ViewPrivilege `json:"privilege"`
	AdditionalProperties map[string]interface{}
}

type _ViewGrant ViewGrant

// NewViewGrant instantiates a new ViewGrant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewGrant(namespace []string, viewName string, privilege ViewPrivilege, type_ string) *ViewGrant {
	this := ViewGrant{}
	this.Type = type_
	this.Namespace = namespace
	this.ViewName = viewName
	this.Privilege = privilege
	return &this
}

// NewViewGrantWithDefaults instantiates a new ViewGrant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewGrantWithDefaults() *ViewGrant {
	this := ViewGrant{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *ViewGrant) GetNamespace() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *ViewGrant) GetNamespaceOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Namespace, true
}

// SetNamespace sets field value
func (o *ViewGrant) SetNamespace(v []string) {
	o.Namespace = v
}

// GetViewName returns the ViewName field value
func (o *ViewGrant) GetViewName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ViewName
}

// GetViewNameOk returns a tuple with the ViewName field value
// and a boolean to check if the value has been set.
func (o *ViewGrant) GetViewNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViewName, true
}

// SetViewName sets field value
func (o *ViewGrant) SetViewName(v string) {
	o.ViewName = v
}

// GetPrivilege returns the Privilege field value
func (o *ViewGrant) GetPrivilege() ViewPrivilege {
	if o == nil {
		var ret ViewPrivilege
		return ret
	}

	return o.Privilege
}

// GetPrivilegeOk returns a tuple with the Privilege field value
// and a boolean to check if the value has been set.
func (o *ViewGrant) GetPrivilegeOk() (*ViewPrivilege, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Privilege, true
}

// SetPrivilege sets field value
func (o *ViewGrant) SetPrivilege(v ViewPrivilege) {
	o.Privilege = v
}

func (o ViewGrant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewGrant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedGrantResource, errGrantResource := json.Marshal(o.GrantResource)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	errGrantResource = json.Unmarshal([]byte(serializedGrantResource), &toSerialize)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	toSerialize["namespace"] = o.Namespace
	toSerialize["viewName"] = o.ViewName
	toSerialize["privilege"] = o.Privilege

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ViewGrant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"viewName",
		"privilege",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type ViewGrantWithoutEmbeddedStruct struct {
		Namespace []string `json:"namespace"`
		ViewName string `json:"viewName"`
		Privilege ViewPrivilege `json:"privilege"`
	}

	varViewGrantWithoutEmbeddedStruct := ViewGrantWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varViewGrantWithoutEmbeddedStruct)
	if err == nil {
		varViewGrant := _ViewGrant{}
		varViewGrant.Namespace = varViewGrantWithoutEmbeddedStruct.Namespace
		varViewGrant.ViewName = varViewGrantWithoutEmbeddedStruct.ViewName
		varViewGrant.Privilege = varViewGrantWithoutEmbeddedStruct.Privilege
		*o = ViewGrant(varViewGrant)
	} else {
		return err
	}

	varViewGrant := _ViewGrant{}

	err = json.Unmarshal(data, &varViewGrant)
	if err == nil {
		o.GrantResource = varViewGrant.GrantResource
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "viewName")
		delete(additionalProperties, "privilege")

		// remove fields from embedded structs
		reflectGrantResource := reflect.ValueOf(o.GrantResource)
		for i := 0; i < reflectGrantResource.Type().NumField(); i++ {
			t := reflectGrantResource.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableViewGrant struct {
	value *ViewGrant
	isSet bool
}

func (v NullableViewGrant) Get() *ViewGrant {
	return v.value
}

func (v *NullableViewGrant) Set(val *ViewGrant) {
	v.value = val
	v.isSet = true
}

func (v NullableViewGrant) IsSet() bool {
	return v.isSet
}

func (v *NullableViewGrant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewGrant(val *ViewGrant) *NullableViewGrant {
	return &NullableViewGrant{value: val, isSet: true}
}

func (v NullableViewGrant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewGrant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


