/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the PolicyGrant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyGrant{}

// PolicyGrant struct for PolicyGrant
type PolicyGrant struct {
	GrantResource
	Namespace            []string        `json:"namespace"`
	PolicyName           string          `json:"policyName"`
	Privilege            PolicyPrivilege `json:"privilege"`
	AdditionalProperties map[string]interface{}
}

type _PolicyGrant PolicyGrant

// NewPolicyGrant instantiates a new PolicyGrant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyGrant(namespace []string, policyName string, privilege PolicyPrivilege, type_ string) *PolicyGrant {
	this := PolicyGrant{}
	this.Type = type_
	this.Namespace = namespace
	this.PolicyName = policyName
	this.Privilege = privilege
	return &this
}

// NewPolicyGrantWithDefaults instantiates a new PolicyGrant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyGrantWithDefaults() *PolicyGrant {
	this := PolicyGrant{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *PolicyGrant) GetNamespace() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *PolicyGrant) GetNamespaceOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Namespace, true
}

// SetNamespace sets field value
func (o *PolicyGrant) SetNamespace(v []string) {
	o.Namespace = v
}

// GetPolicyName returns the PolicyName field value
func (o *PolicyGrant) GetPolicyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyName
}

// GetPolicyNameOk returns a tuple with the PolicyName field value
// and a boolean to check if the value has been set.
func (o *PolicyGrant) GetPolicyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyName, true
}

// SetPolicyName sets field value
func (o *PolicyGrant) SetPolicyName(v string) {
	o.PolicyName = v
}

// GetPrivilege returns the Privilege field value
func (o *PolicyGrant) GetPrivilege() PolicyPrivilege {
	if o == nil {
		var ret PolicyPrivilege
		return ret
	}

	return o.Privilege
}

// GetPrivilegeOk returns a tuple with the Privilege field value
// and a boolean to check if the value has been set.
func (o *PolicyGrant) GetPrivilegeOk() (*PolicyPrivilege, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Privilege, true
}

// SetPrivilege sets field value
func (o *PolicyGrant) SetPrivilege(v PolicyPrivilege) {
	o.Privilege = v
}

func (o PolicyGrant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyGrant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedGrantResource, errGrantResource := json.Marshal(o.GrantResource)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	errGrantResource = json.Unmarshal([]byte(serializedGrantResource), &toSerialize)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	toSerialize["namespace"] = o.Namespace
	toSerialize["policyName"] = o.PolicyName
	toSerialize["privilege"] = o.Privilege

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PolicyGrant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"policyName",
		"privilege",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type PolicyGrantWithoutEmbeddedStruct struct {
		Namespace  []string        `json:"namespace"`
		PolicyName string          `json:"policyName"`
		Privilege  PolicyPrivilege `json:"privilege"`
	}

	varPolicyGrantWithoutEmbeddedStruct := PolicyGrantWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varPolicyGrantWithoutEmbeddedStruct)
	if err == nil {
		varPolicyGrant := _PolicyGrant{}
		varPolicyGrant.Namespace = varPolicyGrantWithoutEmbeddedStruct.Namespace
		varPolicyGrant.PolicyName = varPolicyGrantWithoutEmbeddedStruct.PolicyName
		varPolicyGrant.Privilege = varPolicyGrantWithoutEmbeddedStruct.Privilege
		*o = PolicyGrant(varPolicyGrant)
	} else {
		return err
	}

	varPolicyGrant := _PolicyGrant{}

	err = json.Unmarshal(data, &varPolicyGrant)
	if err == nil {
		o.GrantResource = varPolicyGrant.GrantResource
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "policyName")
		delete(additionalProperties, "privilege")

		// remove fields from embedded structs
		reflectGrantResource := reflect.ValueOf(o.GrantResource)
		for i := 0; i < reflectGrantResource.Type().NumField(); i++ {
			t := reflectGrantResource.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePolicyGrant struct {
	value *PolicyGrant
	isSet bool
}

func (v NullablePolicyGrant) Get() *PolicyGrant {
	return v.value
}

func (v *NullablePolicyGrant) Set(val *PolicyGrant) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyGrant) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyGrant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyGrant(val *PolicyGrant) *NullablePolicyGrant {
	return &NullablePolicyGrant{value: val, isSet: true}
}

func (v NullablePolicyGrant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyGrant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
