/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the Catalog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Catalog{}

// Catalog A catalog object. A catalog may be internal or external. External catalogs are managed entirely by an external catalog interface. Third party catalogs may be other Iceberg REST implementations or other services with their own proprietary APIs
type Catalog struct {
	// the type of catalog - internal or external
	Type string `json:"type"`
	// The name of the catalog
	Name       string            `json:"name" validate:"regexp=^(?!\\\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\\\$).*$"`
	Properties CatalogProperties `json:"properties"`
	// The creation time represented as unix epoch timestamp in milliseconds
	CreateTimestamp *int64 `json:"createTimestamp,omitempty"`
	// The last update time represented as unix epoch timestamp in milliseconds
	LastUpdateTimestamp *int64 `json:"lastUpdateTimestamp,omitempty"`
	// The version of the catalog object used to determine if the catalog metadata has changed
	EntityVersion        *int32            `json:"entityVersion,omitempty"`
	StorageConfigInfo    StorageConfigInfo `json:"storageConfigInfo"`
	AdditionalProperties map[string]interface{}
}

type _Catalog Catalog

// NewCatalog instantiates a new Catalog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalog(type_ string, name string, properties CatalogProperties, storageConfigInfo StorageConfigInfo) *Catalog {
	this := Catalog{}
	this.Type = type_
	this.Name = name
	this.Properties = properties
	this.StorageConfigInfo = storageConfigInfo
	return &this
}

// NewCatalogWithDefaults instantiates a new Catalog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogWithDefaults() *Catalog {
	this := Catalog{}
	var type_ string = "INTERNAL"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *Catalog) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Catalog) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Catalog) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *Catalog) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Catalog) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Catalog) SetName(v string) {
	o.Name = v
}

// GetProperties returns the Properties field value
func (o *Catalog) GetProperties() CatalogProperties {
	if o == nil {
		var ret CatalogProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *Catalog) GetPropertiesOk() (*CatalogProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *Catalog) SetProperties(v CatalogProperties) {
	o.Properties = v
}

// GetCreateTimestamp returns the CreateTimestamp field value if set, zero value otherwise.
func (o *Catalog) GetCreateTimestamp() int64 {
	if o == nil || IsNil(o.CreateTimestamp) {
		var ret int64
		return ret
	}
	return *o.CreateTimestamp
}

// GetCreateTimestampOk returns a tuple with the CreateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Catalog) GetCreateTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.CreateTimestamp) {
		return nil, false
	}
	return o.CreateTimestamp, true
}

// HasCreateTimestamp returns a boolean if a field has been set.
func (o *Catalog) HasCreateTimestamp() bool {
	if o != nil && !IsNil(o.CreateTimestamp) {
		return true
	}

	return false
}

// SetCreateTimestamp gets a reference to the given int64 and assigns it to the CreateTimestamp field.
func (o *Catalog) SetCreateTimestamp(v int64) {
	o.CreateTimestamp = &v
}

// GetLastUpdateTimestamp returns the LastUpdateTimestamp field value if set, zero value otherwise.
func (o *Catalog) GetLastUpdateTimestamp() int64 {
	if o == nil || IsNil(o.LastUpdateTimestamp) {
		var ret int64
		return ret
	}
	return *o.LastUpdateTimestamp
}

// GetLastUpdateTimestampOk returns a tuple with the LastUpdateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Catalog) GetLastUpdateTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdateTimestamp) {
		return nil, false
	}
	return o.LastUpdateTimestamp, true
}

// HasLastUpdateTimestamp returns a boolean if a field has been set.
func (o *Catalog) HasLastUpdateTimestamp() bool {
	if o != nil && !IsNil(o.LastUpdateTimestamp) {
		return true
	}

	return false
}

// SetLastUpdateTimestamp gets a reference to the given int64 and assigns it to the LastUpdateTimestamp field.
func (o *Catalog) SetLastUpdateTimestamp(v int64) {
	o.LastUpdateTimestamp = &v
}

// GetEntityVersion returns the EntityVersion field value if set, zero value otherwise.
func (o *Catalog) GetEntityVersion() int32 {
	if o == nil || IsNil(o.EntityVersion) {
		var ret int32
		return ret
	}
	return *o.EntityVersion
}

// GetEntityVersionOk returns a tuple with the EntityVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Catalog) GetEntityVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.EntityVersion) {
		return nil, false
	}
	return o.EntityVersion, true
}

// HasEntityVersion returns a boolean if a field has been set.
func (o *Catalog) HasEntityVersion() bool {
	if o != nil && !IsNil(o.EntityVersion) {
		return true
	}

	return false
}

// SetEntityVersion gets a reference to the given int32 and assigns it to the EntityVersion field.
func (o *Catalog) SetEntityVersion(v int32) {
	o.EntityVersion = &v
}

// GetStorageConfigInfo returns the StorageConfigInfo field value
func (o *Catalog) GetStorageConfigInfo() StorageConfigInfo {
	if o == nil {
		var ret StorageConfigInfo
		return ret
	}

	return o.StorageConfigInfo
}

// GetStorageConfigInfoOk returns a tuple with the StorageConfigInfo field value
// and a boolean to check if the value has been set.
func (o *Catalog) GetStorageConfigInfoOk() (*StorageConfigInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageConfigInfo, true
}

// SetStorageConfigInfo sets field value
func (o *Catalog) SetStorageConfigInfo(v StorageConfigInfo) {
	o.StorageConfigInfo = v
}

func (o Catalog) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Catalog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["properties"] = o.Properties
	if !IsNil(o.CreateTimestamp) {
		toSerialize["createTimestamp"] = o.CreateTimestamp
	}
	if !IsNil(o.LastUpdateTimestamp) {
		toSerialize["lastUpdateTimestamp"] = o.LastUpdateTimestamp
	}
	if !IsNil(o.EntityVersion) {
		toSerialize["entityVersion"] = o.EntityVersion
	}
	toSerialize["storageConfigInfo"] = o.StorageConfigInfo

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Catalog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"properties",
		"storageConfigInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalog := _Catalog{}

	err = json.Unmarshal(data, &varCatalog)

	if err != nil {
		return err
	}

	*o = Catalog(varCatalog)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "properties")
		delete(additionalProperties, "createTimestamp")
		delete(additionalProperties, "lastUpdateTimestamp")
		delete(additionalProperties, "entityVersion")
		delete(additionalProperties, "storageConfigInfo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCatalog struct {
	value *Catalog
	isSet bool
}

func (v NullableCatalog) Get() *Catalog {
	return v.value
}

func (v *NullableCatalog) Set(val *Catalog) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalog) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalog(val *Catalog) *NullableCatalog {
	return &NullableCatalog{value: val, isSet: true}
}

func (v NullableCatalog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
