/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the PolarisCatalog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolarisCatalog{}

// PolarisCatalog The base catalog type - this contains all the fields necessary to construct an INTERNAL catalog
type PolarisCatalog struct {
	Catalog
	AdditionalProperties map[string]interface{}
}

type _PolarisCatalog PolarisCatalog

// NewPolarisCatalog instantiates a new PolarisCatalog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolarisCatalog(type_ string, name string, properties CatalogProperties, storageConfigInfo StorageConfigInfo) *PolarisCatalog {
	this := PolarisCatalog{}
	this.Type = type_
	this.Name = name
	this.Properties = properties
	this.StorageConfigInfo = storageConfigInfo
	return &this
}

// NewPolarisCatalogWithDefaults instantiates a new PolarisCatalog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolarisCatalogWithDefaults() *PolarisCatalog {
	this := PolarisCatalog{}
	return &this
}

func (o PolarisCatalog) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolarisCatalog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PolarisCatalog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"properties",
		"storageConfigInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolarisCatalog := _PolarisCatalog{}

	err = json.Unmarshal(data, &varPolarisCatalog)

	if err != nil {
		return err
	}

	*o = PolarisCatalog(varPolarisCatalog)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePolarisCatalog struct {
	value *PolarisCatalog
	isSet bool
}

func (v NullablePolarisCatalog) Get() *PolarisCatalog {
	return v.value
}

func (v *NullablePolarisCatalog) Set(val *PolarisCatalog) {
	v.value = val
	v.isSet = true
}

func (v NullablePolarisCatalog) IsSet() bool {
	return v.isSet
}

func (v *NullablePolarisCatalog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolarisCatalog(val *PolarisCatalog) *NullablePolarisCatalog {
	return &NullablePolarisCatalog{value: val, isSet: true}
}

func (v NullablePolarisCatalog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolarisCatalog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


