/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
)

// checks if the PrincipalWithCredentialsCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrincipalWithCredentialsCredentials{}

// PrincipalWithCredentialsCredentials struct for PrincipalWithCredentialsCredentials
type PrincipalWithCredentialsCredentials struct {
	ClientId *string `json:"clientId,omitempty"`
	ClientSecret *string `json:"clientSecret,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PrincipalWithCredentialsCredentials PrincipalWithCredentialsCredentials

// NewPrincipalWithCredentialsCredentials instantiates a new PrincipalWithCredentialsCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipalWithCredentialsCredentials() *PrincipalWithCredentialsCredentials {
	this := PrincipalWithCredentialsCredentials{}
	return &this
}

// NewPrincipalWithCredentialsCredentialsWithDefaults instantiates a new PrincipalWithCredentialsCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalWithCredentialsCredentialsWithDefaults() *PrincipalWithCredentialsCredentials {
	this := PrincipalWithCredentialsCredentials{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *PrincipalWithCredentialsCredentials) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalWithCredentialsCredentials) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *PrincipalWithCredentialsCredentials) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *PrincipalWithCredentialsCredentials) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *PrincipalWithCredentialsCredentials) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalWithCredentialsCredentials) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *PrincipalWithCredentialsCredentials) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *PrincipalWithCredentialsCredentials) SetClientSecret(v string) {
	o.ClientSecret = &v
}

func (o PrincipalWithCredentialsCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrincipalWithCredentialsCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrincipalWithCredentialsCredentials) UnmarshalJSON(data []byte) (err error) {
	varPrincipalWithCredentialsCredentials := _PrincipalWithCredentialsCredentials{}

	err = json.Unmarshal(data, &varPrincipalWithCredentialsCredentials)

	if err != nil {
		return err
	}

	*o = PrincipalWithCredentialsCredentials(varPrincipalWithCredentialsCredentials)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "clientId")
		delete(additionalProperties, "clientSecret")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrincipalWithCredentialsCredentials struct {
	value *PrincipalWithCredentialsCredentials
	isSet bool
}

func (v NullablePrincipalWithCredentialsCredentials) Get() *PrincipalWithCredentialsCredentials {
	return v.value
}

func (v *NullablePrincipalWithCredentialsCredentials) Set(val *PrincipalWithCredentialsCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipalWithCredentialsCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipalWithCredentialsCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipalWithCredentialsCredentials(val *PrincipalWithCredentialsCredentials) *NullablePrincipalWithCredentialsCredentials {
	return &NullablePrincipalWithCredentialsCredentials{value: val, isSet: true}
}

func (v NullablePrincipalWithCredentialsCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipalWithCredentialsCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


