/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the AzureStorageConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureStorageConfigInfo{}

// AzureStorageConfigInfo azure storage configuration info
type AzureStorageConfigInfo struct {
	StorageConfigInfo
	// the tenant id that the storage accounts belong to
	TenantId string `json:"tenantId"`
	// the name of the azure client application
	MultiTenantAppName *string `json:"multiTenantAppName,omitempty"`
	// URL to the Azure permissions request page
	ConsentUrl           *string `json:"consentUrl,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AzureStorageConfigInfo AzureStorageConfigInfo

// NewAzureStorageConfigInfo instantiates a new AzureStorageConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureStorageConfigInfo(tenantId string, storageType string) *AzureStorageConfigInfo {
	this := AzureStorageConfigInfo{}
	this.StorageType = storageType
	this.TenantId = tenantId
	return &this
}

// NewAzureStorageConfigInfoWithDefaults instantiates a new AzureStorageConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureStorageConfigInfoWithDefaults() *AzureStorageConfigInfo {
	this := AzureStorageConfigInfo{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *AzureStorageConfigInfo) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *AzureStorageConfigInfo) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *AzureStorageConfigInfo) SetTenantId(v string) {
	o.TenantId = v
}

// GetMultiTenantAppName returns the MultiTenantAppName field value if set, zero value otherwise.
func (o *AzureStorageConfigInfo) GetMultiTenantAppName() string {
	if o == nil || IsNil(o.MultiTenantAppName) {
		var ret string
		return ret
	}
	return *o.MultiTenantAppName
}

// GetMultiTenantAppNameOk returns a tuple with the MultiTenantAppName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureStorageConfigInfo) GetMultiTenantAppNameOk() (*string, bool) {
	if o == nil || IsNil(o.MultiTenantAppName) {
		return nil, false
	}
	return o.MultiTenantAppName, true
}

// HasMultiTenantAppName returns a boolean if a field has been set.
func (o *AzureStorageConfigInfo) HasMultiTenantAppName() bool {
	if o != nil && !IsNil(o.MultiTenantAppName) {
		return true
	}

	return false
}

// SetMultiTenantAppName gets a reference to the given string and assigns it to the MultiTenantAppName field.
func (o *AzureStorageConfigInfo) SetMultiTenantAppName(v string) {
	o.MultiTenantAppName = &v
}

// GetConsentUrl returns the ConsentUrl field value if set, zero value otherwise.
func (o *AzureStorageConfigInfo) GetConsentUrl() string {
	if o == nil || IsNil(o.ConsentUrl) {
		var ret string
		return ret
	}
	return *o.ConsentUrl
}

// GetConsentUrlOk returns a tuple with the ConsentUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureStorageConfigInfo) GetConsentUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ConsentUrl) {
		return nil, false
	}
	return o.ConsentUrl, true
}

// HasConsentUrl returns a boolean if a field has been set.
func (o *AzureStorageConfigInfo) HasConsentUrl() bool {
	if o != nil && !IsNil(o.ConsentUrl) {
		return true
	}

	return false
}

// SetConsentUrl gets a reference to the given string and assigns it to the ConsentUrl field.
func (o *AzureStorageConfigInfo) SetConsentUrl(v string) {
	o.ConsentUrl = &v
}

func (o AzureStorageConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureStorageConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	if !IsNil(o.MultiTenantAppName) {
		toSerialize["multiTenantAppName"] = o.MultiTenantAppName
	}
	if !IsNil(o.ConsentUrl) {
		toSerialize["consentUrl"] = o.ConsentUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AzureStorageConfigInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"storageType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAzureStorageConfigInfo := _AzureStorageConfigInfo{}

	err = json.Unmarshal(data, &varAzureStorageConfigInfo)

	if err != nil {
		return err
	}

	*o = AzureStorageConfigInfo(varAzureStorageConfigInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "multiTenantAppName")
		delete(additionalProperties, "consentUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAzureStorageConfigInfo struct {
	value *AzureStorageConfigInfo
	isSet bool
}

func (v NullableAzureStorageConfigInfo) Get() *AzureStorageConfigInfo {
	return v.value
}

func (v *NullableAzureStorageConfigInfo) Set(val *AzureStorageConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureStorageConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureStorageConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureStorageConfigInfo(val *AzureStorageConfigInfo) *NullableAzureStorageConfigInfo {
	return &NullableAzureStorageConfigInfo{value: val, isSet: true}
}

func (v NullableAzureStorageConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureStorageConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
