/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the Principal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Principal{}

// Principal A Polaris principal.
type Principal struct {
	Name string `json:"name" validate:"regexp=^(?!\\\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\\\$).*$"`
	// The output-only OAuth clientId associated with this principal if applicable
	ClientId            *string            `json:"clientId,omitempty"`
	Properties          *map[string]string `json:"properties,omitempty"`
	CreateTimestamp     *int64             `json:"createTimestamp,omitempty"`
	LastUpdateTimestamp *int64             `json:"lastUpdateTimestamp,omitempty"`
	// The version of the principal object used to determine if the principal metadata has changed
	EntityVersion        *int32 `json:"entityVersion,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Principal Principal

// NewPrincipal instantiates a new Principal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipal(name string) *Principal {
	this := Principal{}
	this.Name = name
	return &this
}

// NewPrincipalWithDefaults instantiates a new Principal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalWithDefaults() *Principal {
	this := Principal{}
	return &this
}

// GetName returns the Name field value
func (o *Principal) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Principal) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Principal) SetName(v string) {
	o.Name = v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *Principal) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *Principal) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *Principal) SetClientId(v string) {
	o.ClientId = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *Principal) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *Principal) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *Principal) SetProperties(v map[string]string) {
	o.Properties = &v
}

// GetCreateTimestamp returns the CreateTimestamp field value if set, zero value otherwise.
func (o *Principal) GetCreateTimestamp() int64 {
	if o == nil || IsNil(o.CreateTimestamp) {
		var ret int64
		return ret
	}
	return *o.CreateTimestamp
}

// GetCreateTimestampOk returns a tuple with the CreateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetCreateTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.CreateTimestamp) {
		return nil, false
	}
	return o.CreateTimestamp, true
}

// HasCreateTimestamp returns a boolean if a field has been set.
func (o *Principal) HasCreateTimestamp() bool {
	if o != nil && !IsNil(o.CreateTimestamp) {
		return true
	}

	return false
}

// SetCreateTimestamp gets a reference to the given int64 and assigns it to the CreateTimestamp field.
func (o *Principal) SetCreateTimestamp(v int64) {
	o.CreateTimestamp = &v
}

// GetLastUpdateTimestamp returns the LastUpdateTimestamp field value if set, zero value otherwise.
func (o *Principal) GetLastUpdateTimestamp() int64 {
	if o == nil || IsNil(o.LastUpdateTimestamp) {
		var ret int64
		return ret
	}
	return *o.LastUpdateTimestamp
}

// GetLastUpdateTimestampOk returns a tuple with the LastUpdateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetLastUpdateTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdateTimestamp) {
		return nil, false
	}
	return o.LastUpdateTimestamp, true
}

// HasLastUpdateTimestamp returns a boolean if a field has been set.
func (o *Principal) HasLastUpdateTimestamp() bool {
	if o != nil && !IsNil(o.LastUpdateTimestamp) {
		return true
	}

	return false
}

// SetLastUpdateTimestamp gets a reference to the given int64 and assigns it to the LastUpdateTimestamp field.
func (o *Principal) SetLastUpdateTimestamp(v int64) {
	o.LastUpdateTimestamp = &v
}

// GetEntityVersion returns the EntityVersion field value if set, zero value otherwise.
func (o *Principal) GetEntityVersion() int32 {
	if o == nil || IsNil(o.EntityVersion) {
		var ret int32
		return ret
	}
	return *o.EntityVersion
}

// GetEntityVersionOk returns a tuple with the EntityVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetEntityVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.EntityVersion) {
		return nil, false
	}
	return o.EntityVersion, true
}

// HasEntityVersion returns a boolean if a field has been set.
func (o *Principal) HasEntityVersion() bool {
	if o != nil && !IsNil(o.EntityVersion) {
		return true
	}

	return false
}

// SetEntityVersion gets a reference to the given int32 and assigns it to the EntityVersion field.
func (o *Principal) SetEntityVersion(v int32) {
	o.EntityVersion = &v
}

func (o Principal) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Principal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.CreateTimestamp) {
		toSerialize["createTimestamp"] = o.CreateTimestamp
	}
	if !IsNil(o.LastUpdateTimestamp) {
		toSerialize["lastUpdateTimestamp"] = o.LastUpdateTimestamp
	}
	if !IsNil(o.EntityVersion) {
		toSerialize["entityVersion"] = o.EntityVersion
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Principal) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrincipal := _Principal{}

	err = json.Unmarshal(data, &varPrincipal)

	if err != nil {
		return err
	}

	*o = Principal(varPrincipal)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "clientId")
		delete(additionalProperties, "properties")
		delete(additionalProperties, "createTimestamp")
		delete(additionalProperties, "lastUpdateTimestamp")
		delete(additionalProperties, "entityVersion")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrincipal struct {
	value *Principal
	isSet bool
}

func (v NullablePrincipal) Get() *Principal {
	return v.value
}

func (v *NullablePrincipal) Set(val *Principal) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipal) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipal(val *Principal) *NullablePrincipal {
	return &NullablePrincipal{value: val, isSet: true}
}

func (v NullablePrincipal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
