/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the CatalogGrant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogGrant{}

// CatalogGrant struct for CatalogGrant
type CatalogGrant struct {
	GrantResource
	Privilege            CatalogPrivilege `json:"privilege"`
	AdditionalProperties map[string]interface{}
}

type _CatalogGrant CatalogGrant

// NewCatalogGrant instantiates a new CatalogGrant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogGrant(privilege CatalogPrivilege, type_ string) *CatalogGrant {
	this := CatalogGrant{}
	this.Type = type_
	this.Privilege = privilege
	return &this
}

// NewCatalogGrantWithDefaults instantiates a new CatalogGrant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogGrantWithDefaults() *CatalogGrant {
	this := CatalogGrant{}
	return &this
}

// GetPrivilege returns the Privilege field value
func (o *CatalogGrant) GetPrivilege() CatalogPrivilege {
	if o == nil {
		var ret CatalogPrivilege
		return ret
	}

	return o.Privilege
}

// GetPrivilegeOk returns a tuple with the Privilege field value
// and a boolean to check if the value has been set.
func (o *CatalogGrant) GetPrivilegeOk() (*CatalogPrivilege, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Privilege, true
}

// SetPrivilege sets field value
func (o *CatalogGrant) SetPrivilege(v CatalogPrivilege) {
	o.Privilege = v
}

func (o CatalogGrant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogGrant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedGrantResource, errGrantResource := json.Marshal(o.GrantResource)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	errGrantResource = json.Unmarshal([]byte(serializedGrantResource), &toSerialize)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	toSerialize["privilege"] = o.Privilege

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CatalogGrant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"privilege",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type CatalogGrantWithoutEmbeddedStruct struct {
		Privilege CatalogPrivilege `json:"privilege"`
	}

	varCatalogGrantWithoutEmbeddedStruct := CatalogGrantWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varCatalogGrantWithoutEmbeddedStruct)
	if err == nil {
		varCatalogGrant := _CatalogGrant{}
		varCatalogGrant.Privilege = varCatalogGrantWithoutEmbeddedStruct.Privilege
		*o = CatalogGrant(varCatalogGrant)
	} else {
		return err
	}

	varCatalogGrant := _CatalogGrant{}

	err = json.Unmarshal(data, &varCatalogGrant)
	if err == nil {
		o.GrantResource = varCatalogGrant.GrantResource
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "privilege")

		// remove fields from embedded structs
		reflectGrantResource := reflect.ValueOf(o.GrantResource)
		for i := 0; i < reflectGrantResource.Type().NumField(); i++ {
			t := reflectGrantResource.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCatalogGrant struct {
	value *CatalogGrant
	isSet bool
}

func (v NullableCatalogGrant) Get() *CatalogGrant {
	return v.value
}

func (v *NullableCatalogGrant) Set(val *CatalogGrant) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogGrant) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogGrant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogGrant(val *CatalogGrant) *NullableCatalogGrant {
	return &NullableCatalogGrant{value: val, isSet: true}
}

func (v NullableCatalogGrant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogGrant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
