/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the ServiceIdentityInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceIdentityInfo{}

// ServiceIdentityInfo Identity metadata for the Polaris service used to access external resources.
type ServiceIdentityInfo struct {
	// The type of identity used to access external resources
	IdentityType         string `json:"identityType"`
	AdditionalProperties map[string]interface{}
}

type _ServiceIdentityInfo ServiceIdentityInfo

// NewServiceIdentityInfo instantiates a new ServiceIdentityInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceIdentityInfo(identityType string) *ServiceIdentityInfo {
	this := ServiceIdentityInfo{}
	this.IdentityType = identityType
	return &this
}

// NewServiceIdentityInfoWithDefaults instantiates a new ServiceIdentityInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceIdentityInfoWithDefaults() *ServiceIdentityInfo {
	this := ServiceIdentityInfo{}
	return &this
}

// GetIdentityType returns the IdentityType field value
func (o *ServiceIdentityInfo) GetIdentityType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentityType
}

// GetIdentityTypeOk returns a tuple with the IdentityType field value
// and a boolean to check if the value has been set.
func (o *ServiceIdentityInfo) GetIdentityTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentityType, true
}

// SetIdentityType sets field value
func (o *ServiceIdentityInfo) SetIdentityType(v string) {
	o.IdentityType = v
}

func (o ServiceIdentityInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceIdentityInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identityType"] = o.IdentityType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceIdentityInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identityType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceIdentityInfo := _ServiceIdentityInfo{}

	err = json.Unmarshal(data, &varServiceIdentityInfo)

	if err != nil {
		return err
	}

	*o = ServiceIdentityInfo(varServiceIdentityInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "identityType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceIdentityInfo struct {
	value *ServiceIdentityInfo
	isSet bool
}

func (v NullableServiceIdentityInfo) Get() *ServiceIdentityInfo {
	return v.value
}

func (v *NullableServiceIdentityInfo) Set(val *ServiceIdentityInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceIdentityInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceIdentityInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceIdentityInfo(val *ServiceIdentityInfo) *NullableServiceIdentityInfo {
	return &NullableServiceIdentityInfo{value: val, isSet: true}
}

func (v NullableServiceIdentityInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceIdentityInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
