/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the PrincipalWithCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrincipalWithCredentials{}

// PrincipalWithCredentials A user with its client id and secret. This type is returned when a new principal is created or when its credentials are rotated
type PrincipalWithCredentials struct {
	Principal Principal `json:"principal"`
	Credentials PrincipalWithCredentialsCredentials `json:"credentials"`
	AdditionalProperties map[string]interface{}
}

type _PrincipalWithCredentials PrincipalWithCredentials

// NewPrincipalWithCredentials instantiates a new PrincipalWithCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipalWithCredentials(principal Principal, credentials PrincipalWithCredentialsCredentials) *PrincipalWithCredentials {
	this := PrincipalWithCredentials{}
	this.Principal = principal
	this.Credentials = credentials
	return &this
}

// NewPrincipalWithCredentialsWithDefaults instantiates a new PrincipalWithCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalWithCredentialsWithDefaults() *PrincipalWithCredentials {
	this := PrincipalWithCredentials{}
	return &this
}

// GetPrincipal returns the Principal field value
func (o *PrincipalWithCredentials) GetPrincipal() Principal {
	if o == nil {
		var ret Principal
		return ret
	}

	return o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value
// and a boolean to check if the value has been set.
func (o *PrincipalWithCredentials) GetPrincipalOk() (*Principal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Principal, true
}

// SetPrincipal sets field value
func (o *PrincipalWithCredentials) SetPrincipal(v Principal) {
	o.Principal = v
}

// GetCredentials returns the Credentials field value
func (o *PrincipalWithCredentials) GetCredentials() PrincipalWithCredentialsCredentials {
	if o == nil {
		var ret PrincipalWithCredentialsCredentials
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *PrincipalWithCredentials) GetCredentialsOk() (*PrincipalWithCredentialsCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credentials, true
}

// SetCredentials sets field value
func (o *PrincipalWithCredentials) SetCredentials(v PrincipalWithCredentialsCredentials) {
	o.Credentials = v
}

func (o PrincipalWithCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrincipalWithCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["principal"] = o.Principal
	toSerialize["credentials"] = o.Credentials

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrincipalWithCredentials) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"principal",
		"credentials",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrincipalWithCredentials := _PrincipalWithCredentials{}

	err = json.Unmarshal(data, &varPrincipalWithCredentials)

	if err != nil {
		return err
	}

	*o = PrincipalWithCredentials(varPrincipalWithCredentials)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "principal")
		delete(additionalProperties, "credentials")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrincipalWithCredentials struct {
	value *PrincipalWithCredentials
	isSet bool
}

func (v NullablePrincipalWithCredentials) Get() *PrincipalWithCredentials {
	return v.value
}

func (v *NullablePrincipalWithCredentials) Set(val *PrincipalWithCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipalWithCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipalWithCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipalWithCredentials(val *PrincipalWithCredentials) *NullablePrincipalWithCredentials {
	return &NullablePrincipalWithCredentials{value: val, isSet: true}
}

func (v NullablePrincipalWithCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipalWithCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


