/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the TableGrant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableGrant{}

// TableGrant struct for TableGrant
type TableGrant struct {
	GrantResource
	Namespace            []string       `json:"namespace"`
	TableName            string         `json:"tableName"`
	Privilege            TablePrivilege `json:"privilege"`
	AdditionalProperties map[string]interface{}
}

type _TableGrant TableGrant

// NewTableGrant instantiates a new TableGrant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableGrant(namespace []string, tableName string, privilege TablePrivilege, type_ string) *TableGrant {
	this := TableGrant{}
	this.Type = type_
	this.Namespace = namespace
	this.TableName = tableName
	this.Privilege = privilege
	return &this
}

// NewTableGrantWithDefaults instantiates a new TableGrant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableGrantWithDefaults() *TableGrant {
	this := TableGrant{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *TableGrant) GetNamespace() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *TableGrant) GetNamespaceOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Namespace, true
}

// SetNamespace sets field value
func (o *TableGrant) SetNamespace(v []string) {
	o.Namespace = v
}

// GetTableName returns the TableName field value
func (o *TableGrant) GetTableName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TableName
}

// GetTableNameOk returns a tuple with the TableName field value
// and a boolean to check if the value has been set.
func (o *TableGrant) GetTableNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TableName, true
}

// SetTableName sets field value
func (o *TableGrant) SetTableName(v string) {
	o.TableName = v
}

// GetPrivilege returns the Privilege field value
func (o *TableGrant) GetPrivilege() TablePrivilege {
	if o == nil {
		var ret TablePrivilege
		return ret
	}

	return o.Privilege
}

// GetPrivilegeOk returns a tuple with the Privilege field value
// and a boolean to check if the value has been set.
func (o *TableGrant) GetPrivilegeOk() (*TablePrivilege, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Privilege, true
}

// SetPrivilege sets field value
func (o *TableGrant) SetPrivilege(v TablePrivilege) {
	o.Privilege = v
}

func (o TableGrant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableGrant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedGrantResource, errGrantResource := json.Marshal(o.GrantResource)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	errGrantResource = json.Unmarshal([]byte(serializedGrantResource), &toSerialize)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	toSerialize["namespace"] = o.Namespace
	toSerialize["tableName"] = o.TableName
	toSerialize["privilege"] = o.Privilege

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TableGrant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"tableName",
		"privilege",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type TableGrantWithoutEmbeddedStruct struct {
		Namespace []string       `json:"namespace"`
		TableName string         `json:"tableName"`
		Privilege TablePrivilege `json:"privilege"`
	}

	varTableGrantWithoutEmbeddedStruct := TableGrantWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varTableGrantWithoutEmbeddedStruct)
	if err == nil {
		varTableGrant := _TableGrant{}
		varTableGrant.Namespace = varTableGrantWithoutEmbeddedStruct.Namespace
		varTableGrant.TableName = varTableGrantWithoutEmbeddedStruct.TableName
		varTableGrant.Privilege = varTableGrantWithoutEmbeddedStruct.Privilege
		*o = TableGrant(varTableGrant)
	} else {
		return err
	}

	varTableGrant := _TableGrant{}

	err = json.Unmarshal(data, &varTableGrant)
	if err == nil {
		o.GrantResource = varTableGrant.GrantResource
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "tableName")
		delete(additionalProperties, "privilege")

		// remove fields from embedded structs
		reflectGrantResource := reflect.ValueOf(o.GrantResource)
		for i := 0; i < reflectGrantResource.Type().NumField(); i++ {
			t := reflectGrantResource.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTableGrant struct {
	value *TableGrant
	isSet bool
}

func (v NullableTableGrant) Get() *TableGrant {
	return v.value
}

func (v *NullableTableGrant) Set(val *TableGrant) {
	v.value = val
	v.isSet = true
}

func (v NullableTableGrant) IsSet() bool {
	return v.isSet
}

func (v *NullableTableGrant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableGrant(val *TableGrant) *NullableTableGrant {
	return &NullableTableGrant{value: val, isSet: true}
}

func (v NullableTableGrant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableGrant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
