/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the CatalogRoles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogRoles{}

// CatalogRoles struct for CatalogRoles
type CatalogRoles struct {
	// The list of catalog roles
	Roles                []CatalogRole `json:"roles"`
	AdditionalProperties map[string]interface{}
}

type _CatalogRoles CatalogRoles

// NewCatalogRoles instantiates a new CatalogRoles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogRoles(roles []CatalogRole) *CatalogRoles {
	this := CatalogRoles{}
	this.Roles = roles
	return &this
}

// NewCatalogRolesWithDefaults instantiates a new CatalogRoles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogRolesWithDefaults() *CatalogRoles {
	this := CatalogRoles{}
	return &this
}

// GetRoles returns the Roles field value
func (o *CatalogRoles) GetRoles() []CatalogRole {
	if o == nil {
		var ret []CatalogRole
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *CatalogRoles) GetRolesOk() ([]CatalogRole, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *CatalogRoles) SetRoles(v []CatalogRole) {
	o.Roles = v
}

func (o CatalogRoles) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogRoles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roles"] = o.Roles

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CatalogRoles) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogRoles := _CatalogRoles{}

	err = json.Unmarshal(data, &varCatalogRoles)

	if err != nil {
		return err
	}

	*o = CatalogRoles(varCatalogRoles)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "roles")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCatalogRoles struct {
	value *CatalogRoles
	isSet bool
}

func (v NullableCatalogRoles) Get() *CatalogRoles {
	return v.value
}

func (v *NullableCatalogRoles) Set(val *CatalogRoles) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogRoles) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogRoles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogRoles(val *CatalogRoles) *NullableCatalogRoles {
	return &NullableCatalogRoles{value: val, isSet: true}
}

func (v NullableCatalogRoles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogRoles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
