/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateCatalogRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCatalogRoleRequest{}

// UpdateCatalogRoleRequest Updates to apply to a Catalog Role
type UpdateCatalogRoleRequest struct {
	// The version of the object onto which this update is applied; if the object changed, the update will fail and the caller should retry after fetching the latest version.
	CurrentEntityVersion int32             `json:"currentEntityVersion"`
	Properties           map[string]string `json:"properties"`
	AdditionalProperties map[string]interface{}
}

type _UpdateCatalogRoleRequest UpdateCatalogRoleRequest

// NewUpdateCatalogRoleRequest instantiates a new UpdateCatalogRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCatalogRoleRequest(currentEntityVersion int32, properties map[string]string) *UpdateCatalogRoleRequest {
	this := UpdateCatalogRoleRequest{}
	this.CurrentEntityVersion = currentEntityVersion
	this.Properties = properties
	return &this
}

// NewUpdateCatalogRoleRequestWithDefaults instantiates a new UpdateCatalogRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCatalogRoleRequestWithDefaults() *UpdateCatalogRoleRequest {
	this := UpdateCatalogRoleRequest{}
	return &this
}

// GetCurrentEntityVersion returns the CurrentEntityVersion field value
func (o *UpdateCatalogRoleRequest) GetCurrentEntityVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentEntityVersion
}

// GetCurrentEntityVersionOk returns a tuple with the CurrentEntityVersion field value
// and a boolean to check if the value has been set.
func (o *UpdateCatalogRoleRequest) GetCurrentEntityVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentEntityVersion, true
}

// SetCurrentEntityVersion sets field value
func (o *UpdateCatalogRoleRequest) SetCurrentEntityVersion(v int32) {
	o.CurrentEntityVersion = v
}

// GetProperties returns the Properties field value
func (o *UpdateCatalogRoleRequest) GetProperties() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *UpdateCatalogRoleRequest) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *UpdateCatalogRoleRequest) SetProperties(v map[string]string) {
	o.Properties = v
}

func (o UpdateCatalogRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCatalogRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currentEntityVersion"] = o.CurrentEntityVersion
	toSerialize["properties"] = o.Properties

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateCatalogRoleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currentEntityVersion",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCatalogRoleRequest := _UpdateCatalogRoleRequest{}

	err = json.Unmarshal(data, &varUpdateCatalogRoleRequest)

	if err != nil {
		return err
	}

	*o = UpdateCatalogRoleRequest(varUpdateCatalogRoleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "currentEntityVersion")
		delete(additionalProperties, "properties")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateCatalogRoleRequest struct {
	value *UpdateCatalogRoleRequest
	isSet bool
}

func (v NullableUpdateCatalogRoleRequest) Get() *UpdateCatalogRoleRequest {
	return v.value
}

func (v *NullableUpdateCatalogRoleRequest) Set(val *UpdateCatalogRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCatalogRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCatalogRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCatalogRoleRequest(val *UpdateCatalogRoleRequest) *NullableUpdateCatalogRoleRequest {
	return &NullableUpdateCatalogRoleRequest{value: val, isSet: true}
}

func (v NullableUpdateCatalogRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCatalogRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
