/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the PrincipalRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrincipalRole{}

// PrincipalRole struct for PrincipalRole
type PrincipalRole struct {
	// The name of the role
	Name string `json:"name" validate:"regexp=^(?!\\\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\\\$).*$"`
	// Whether the principal role is a federated role (that is, managed by an external identity provider)
	Federated *bool `json:"federated,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
	CreateTimestamp *int64 `json:"createTimestamp,omitempty"`
	LastUpdateTimestamp *int64 `json:"lastUpdateTimestamp,omitempty"`
	// The version of the principal role object used to determine if the principal role metadata has changed
	EntityVersion *int32 `json:"entityVersion,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PrincipalRole PrincipalRole

// NewPrincipalRole instantiates a new PrincipalRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipalRole(name string) *PrincipalRole {
	this := PrincipalRole{}
	this.Name = name
	var federated bool = false
	this.Federated = &federated
	return &this
}

// NewPrincipalRoleWithDefaults instantiates a new PrincipalRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalRoleWithDefaults() *PrincipalRole {
	this := PrincipalRole{}
	var federated bool = false
	this.Federated = &federated
	return &this
}

// GetName returns the Name field value
func (o *PrincipalRole) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PrincipalRole) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PrincipalRole) SetName(v string) {
	o.Name = v
}

// GetFederated returns the Federated field value if set, zero value otherwise.
func (o *PrincipalRole) GetFederated() bool {
	if o == nil || IsNil(o.Federated) {
		var ret bool
		return ret
	}
	return *o.Federated
}

// GetFederatedOk returns a tuple with the Federated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalRole) GetFederatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Federated) {
		return nil, false
	}
	return o.Federated, true
}

// HasFederated returns a boolean if a field has been set.
func (o *PrincipalRole) HasFederated() bool {
	if o != nil && !IsNil(o.Federated) {
		return true
	}

	return false
}

// SetFederated gets a reference to the given bool and assigns it to the Federated field.
func (o *PrincipalRole) SetFederated(v bool) {
	o.Federated = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *PrincipalRole) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalRole) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *PrincipalRole) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *PrincipalRole) SetProperties(v map[string]string) {
	o.Properties = &v
}

// GetCreateTimestamp returns the CreateTimestamp field value if set, zero value otherwise.
func (o *PrincipalRole) GetCreateTimestamp() int64 {
	if o == nil || IsNil(o.CreateTimestamp) {
		var ret int64
		return ret
	}
	return *o.CreateTimestamp
}

// GetCreateTimestampOk returns a tuple with the CreateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalRole) GetCreateTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.CreateTimestamp) {
		return nil, false
	}
	return o.CreateTimestamp, true
}

// HasCreateTimestamp returns a boolean if a field has been set.
func (o *PrincipalRole) HasCreateTimestamp() bool {
	if o != nil && !IsNil(o.CreateTimestamp) {
		return true
	}

	return false
}

// SetCreateTimestamp gets a reference to the given int64 and assigns it to the CreateTimestamp field.
func (o *PrincipalRole) SetCreateTimestamp(v int64) {
	o.CreateTimestamp = &v
}

// GetLastUpdateTimestamp returns the LastUpdateTimestamp field value if set, zero value otherwise.
func (o *PrincipalRole) GetLastUpdateTimestamp() int64 {
	if o == nil || IsNil(o.LastUpdateTimestamp) {
		var ret int64
		return ret
	}
	return *o.LastUpdateTimestamp
}

// GetLastUpdateTimestampOk returns a tuple with the LastUpdateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalRole) GetLastUpdateTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdateTimestamp) {
		return nil, false
	}
	return o.LastUpdateTimestamp, true
}

// HasLastUpdateTimestamp returns a boolean if a field has been set.
func (o *PrincipalRole) HasLastUpdateTimestamp() bool {
	if o != nil && !IsNil(o.LastUpdateTimestamp) {
		return true
	}

	return false
}

// SetLastUpdateTimestamp gets a reference to the given int64 and assigns it to the LastUpdateTimestamp field.
func (o *PrincipalRole) SetLastUpdateTimestamp(v int64) {
	o.LastUpdateTimestamp = &v
}

// GetEntityVersion returns the EntityVersion field value if set, zero value otherwise.
func (o *PrincipalRole) GetEntityVersion() int32 {
	if o == nil || IsNil(o.EntityVersion) {
		var ret int32
		return ret
	}
	return *o.EntityVersion
}

// GetEntityVersionOk returns a tuple with the EntityVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrincipalRole) GetEntityVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.EntityVersion) {
		return nil, false
	}
	return o.EntityVersion, true
}

// HasEntityVersion returns a boolean if a field has been set.
func (o *PrincipalRole) HasEntityVersion() bool {
	if o != nil && !IsNil(o.EntityVersion) {
		return true
	}

	return false
}

// SetEntityVersion gets a reference to the given int32 and assigns it to the EntityVersion field.
func (o *PrincipalRole) SetEntityVersion(v int32) {
	o.EntityVersion = &v
}

func (o PrincipalRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrincipalRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Federated) {
		toSerialize["federated"] = o.Federated
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.CreateTimestamp) {
		toSerialize["createTimestamp"] = o.CreateTimestamp
	}
	if !IsNil(o.LastUpdateTimestamp) {
		toSerialize["lastUpdateTimestamp"] = o.LastUpdateTimestamp
	}
	if !IsNil(o.EntityVersion) {
		toSerialize["entityVersion"] = o.EntityVersion
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrincipalRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrincipalRole := _PrincipalRole{}

	err = json.Unmarshal(data, &varPrincipalRole)

	if err != nil {
		return err
	}

	*o = PrincipalRole(varPrincipalRole)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "federated")
		delete(additionalProperties, "properties")
		delete(additionalProperties, "createTimestamp")
		delete(additionalProperties, "lastUpdateTimestamp")
		delete(additionalProperties, "entityVersion")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrincipalRole struct {
	value *PrincipalRole
	isSet bool
}

func (v NullablePrincipalRole) Get() *PrincipalRole {
	return v.value
}

func (v *NullablePrincipalRole) Set(val *PrincipalRole) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipalRole) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipalRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipalRole(val *PrincipalRole) *NullablePrincipalRole {
	return &NullablePrincipalRole{value: val, isSet: true}
}

func (v NullablePrincipalRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipalRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


