/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the GrantResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantResource{}

// GrantResource struct for GrantResource
type GrantResource struct {
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _GrantResource GrantResource

// NewGrantResource instantiates a new GrantResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantResource(type_ string) *GrantResource {
	this := GrantResource{}
	this.Type = type_
	return &this
}

// NewGrantResourceWithDefaults instantiates a new GrantResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantResourceWithDefaults() *GrantResource {
	this := GrantResource{}
	return &this
}

// GetType returns the Type field value
func (o *GrantResource) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GrantResource) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GrantResource) SetType(v string) {
	o.Type = v
}

func (o GrantResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GrantResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGrantResource := _GrantResource{}

	err = json.Unmarshal(data, &varGrantResource)

	if err != nil {
		return err
	}

	*o = GrantResource(varGrantResource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGrantResource struct {
	value *GrantResource
	isSet bool
}

func (v NullableGrantResource) Get() *GrantResource {
	return v.value
}

func (v *NullableGrantResource) Set(val *GrantResource) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantResource) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantResource(val *GrantResource) *NullableGrantResource {
	return &NullableGrantResource{value: val, isSet: true}
}

func (v NullableGrantResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


