/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the StorageConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageConfigInfo{}

// StorageConfigInfo A storage configuration used by catalogs
type StorageConfigInfo struct {
	// The cloud provider type this storage is built on. FILE is supported for testing purposes only
	StorageType          string   `json:"storageType"`
	AllowedLocations     []string `json:"allowedLocations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StorageConfigInfo StorageConfigInfo

// NewStorageConfigInfo instantiates a new StorageConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageConfigInfo(storageType string) *StorageConfigInfo {
	this := StorageConfigInfo{}
	this.StorageType = storageType
	return &this
}

// NewStorageConfigInfoWithDefaults instantiates a new StorageConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageConfigInfoWithDefaults() *StorageConfigInfo {
	this := StorageConfigInfo{}
	return &this
}

// GetStorageType returns the StorageType field value
func (o *StorageConfigInfo) GetStorageType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *StorageConfigInfo) GetStorageTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *StorageConfigInfo) SetStorageType(v string) {
	o.StorageType = v
}

// GetAllowedLocations returns the AllowedLocations field value if set, zero value otherwise.
func (o *StorageConfigInfo) GetAllowedLocations() []string {
	if o == nil || IsNil(o.AllowedLocations) {
		var ret []string
		return ret
	}
	return o.AllowedLocations
}

// GetAllowedLocationsOk returns a tuple with the AllowedLocations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageConfigInfo) GetAllowedLocationsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedLocations) {
		return nil, false
	}
	return o.AllowedLocations, true
}

// HasAllowedLocations returns a boolean if a field has been set.
func (o *StorageConfigInfo) HasAllowedLocations() bool {
	if o != nil && !IsNil(o.AllowedLocations) {
		return true
	}

	return false
}

// SetAllowedLocations gets a reference to the given []string and assigns it to the AllowedLocations field.
func (o *StorageConfigInfo) SetAllowedLocations(v []string) {
	o.AllowedLocations = v
}

func (o StorageConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["storageType"] = o.StorageType
	if !IsNil(o.AllowedLocations) {
		toSerialize["allowedLocations"] = o.AllowedLocations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StorageConfigInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"storageType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageConfigInfo := _StorageConfigInfo{}

	err = json.Unmarshal(data, &varStorageConfigInfo)

	if err != nil {
		return err
	}

	*o = StorageConfigInfo(varStorageConfigInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "storageType")
		delete(additionalProperties, "allowedLocations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStorageConfigInfo struct {
	value *StorageConfigInfo
	isSet bool
}

func (v NullableStorageConfigInfo) Get() *StorageConfigInfo {
	return v.value
}

func (v *NullableStorageConfigInfo) Set(val *StorageConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageConfigInfo(val *StorageConfigInfo) *NullableStorageConfigInfo {
	return &NullableStorageConfigInfo{value: val, isSet: true}
}

func (v NullableStorageConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
