/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the AwsIamServiceIdentityInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsIamServiceIdentityInfo{}

// AwsIamServiceIdentityInfo struct for AwsIamServiceIdentityInfo
type AwsIamServiceIdentityInfo struct {
	ServiceIdentityInfo
	// The ARN of the IAM user or IAM role Polaris uses to assume roles and then access external resources.
	IamArn               string `json:"iamArn"`
	AdditionalProperties map[string]interface{}
}

type _AwsIamServiceIdentityInfo AwsIamServiceIdentityInfo

// NewAwsIamServiceIdentityInfo instantiates a new AwsIamServiceIdentityInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsIamServiceIdentityInfo(iamArn string, identityType string) *AwsIamServiceIdentityInfo {
	this := AwsIamServiceIdentityInfo{}
	this.IdentityType = identityType
	this.IamArn = iamArn
	return &this
}

// NewAwsIamServiceIdentityInfoWithDefaults instantiates a new AwsIamServiceIdentityInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsIamServiceIdentityInfoWithDefaults() *AwsIamServiceIdentityInfo {
	this := AwsIamServiceIdentityInfo{}
	return &this
}

// GetIamArn returns the IamArn field value
func (o *AwsIamServiceIdentityInfo) GetIamArn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IamArn
}

// GetIamArnOk returns a tuple with the IamArn field value
// and a boolean to check if the value has been set.
func (o *AwsIamServiceIdentityInfo) GetIamArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IamArn, true
}

// SetIamArn sets field value
func (o *AwsIamServiceIdentityInfo) SetIamArn(v string) {
	o.IamArn = v
}

func (o AwsIamServiceIdentityInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsIamServiceIdentityInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["iamArn"] = o.IamArn

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AwsIamServiceIdentityInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"iamArn",
		"identityType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAwsIamServiceIdentityInfo := _AwsIamServiceIdentityInfo{}

	err = json.Unmarshal(data, &varAwsIamServiceIdentityInfo)

	if err != nil {
		return err
	}

	*o = AwsIamServiceIdentityInfo(varAwsIamServiceIdentityInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "iamArn")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAwsIamServiceIdentityInfo struct {
	value *AwsIamServiceIdentityInfo
	isSet bool
}

func (v NullableAwsIamServiceIdentityInfo) Get() *AwsIamServiceIdentityInfo {
	return v.value
}

func (v *NullableAwsIamServiceIdentityInfo) Set(val *AwsIamServiceIdentityInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsIamServiceIdentityInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsIamServiceIdentityInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsIamServiceIdentityInfo(val *AwsIamServiceIdentityInfo) *NullableAwsIamServiceIdentityInfo {
	return &NullableAwsIamServiceIdentityInfo{value: val, isSet: true}
}

func (v NullableAwsIamServiceIdentityInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsIamServiceIdentityInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
