/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the NamespaceGrant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NamespaceGrant{}

// NamespaceGrant struct for NamespaceGrant
type NamespaceGrant struct {
	GrantResource
	Namespace []string `json:"namespace"`
	Privilege NamespacePrivilege `json:"privilege"`
	AdditionalProperties map[string]interface{}
}

type _NamespaceGrant NamespaceGrant

// NewNamespaceGrant instantiates a new NamespaceGrant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNamespaceGrant(namespace []string, privilege NamespacePrivilege, type_ string) *NamespaceGrant {
	this := NamespaceGrant{}
	this.Type = type_
	this.Namespace = namespace
	this.Privilege = privilege
	return &this
}

// NewNamespaceGrantWithDefaults instantiates a new NamespaceGrant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamespaceGrantWithDefaults() *NamespaceGrant {
	this := NamespaceGrant{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *NamespaceGrant) GetNamespace() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *NamespaceGrant) GetNamespaceOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Namespace, true
}

// SetNamespace sets field value
func (o *NamespaceGrant) SetNamespace(v []string) {
	o.Namespace = v
}

// GetPrivilege returns the Privilege field value
func (o *NamespaceGrant) GetPrivilege() NamespacePrivilege {
	if o == nil {
		var ret NamespacePrivilege
		return ret
	}

	return o.Privilege
}

// GetPrivilegeOk returns a tuple with the Privilege field value
// and a boolean to check if the value has been set.
func (o *NamespaceGrant) GetPrivilegeOk() (*NamespacePrivilege, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Privilege, true
}

// SetPrivilege sets field value
func (o *NamespaceGrant) SetPrivilege(v NamespacePrivilege) {
	o.Privilege = v
}

func (o NamespaceGrant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NamespaceGrant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedGrantResource, errGrantResource := json.Marshal(o.GrantResource)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	errGrantResource = json.Unmarshal([]byte(serializedGrantResource), &toSerialize)
	if errGrantResource != nil {
		return map[string]interface{}{}, errGrantResource
	}
	toSerialize["namespace"] = o.Namespace
	toSerialize["privilege"] = o.Privilege

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NamespaceGrant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"privilege",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type NamespaceGrantWithoutEmbeddedStruct struct {
		Namespace []string `json:"namespace"`
		Privilege NamespacePrivilege `json:"privilege"`
	}

	varNamespaceGrantWithoutEmbeddedStruct := NamespaceGrantWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varNamespaceGrantWithoutEmbeddedStruct)
	if err == nil {
		varNamespaceGrant := _NamespaceGrant{}
		varNamespaceGrant.Namespace = varNamespaceGrantWithoutEmbeddedStruct.Namespace
		varNamespaceGrant.Privilege = varNamespaceGrantWithoutEmbeddedStruct.Privilege
		*o = NamespaceGrant(varNamespaceGrant)
	} else {
		return err
	}

	varNamespaceGrant := _NamespaceGrant{}

	err = json.Unmarshal(data, &varNamespaceGrant)
	if err == nil {
		o.GrantResource = varNamespaceGrant.GrantResource
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "privilege")

		// remove fields from embedded structs
		reflectGrantResource := reflect.ValueOf(o.GrantResource)
		for i := 0; i < reflectGrantResource.Type().NumField(); i++ {
			t := reflectGrantResource.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNamespaceGrant struct {
	value *NamespaceGrant
	isSet bool
}

func (v NullableNamespaceGrant) Get() *NamespaceGrant {
	return v.value
}

func (v *NullableNamespaceGrant) Set(val *NamespaceGrant) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceGrant) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceGrant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceGrant(val *NamespaceGrant) *NullableNamespaceGrant {
	return &NullableNamespaceGrant{value: val, isSet: true}
}

func (v NullableNamespaceGrant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceGrant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


