/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the ImplicitAuthenticationParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImplicitAuthenticationParameters{}

// ImplicitAuthenticationParameters Polaris does not explicitly accept any authentication parameters for the connection. Authentication parameters found in the environment and/or configuration files will be used for this connection.
type ImplicitAuthenticationParameters struct {
	AuthenticationParameters
	AdditionalProperties map[string]interface{}
}

type _ImplicitAuthenticationParameters ImplicitAuthenticationParameters

// NewImplicitAuthenticationParameters instantiates a new ImplicitAuthenticationParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImplicitAuthenticationParameters(authenticationType string) *ImplicitAuthenticationParameters {
	this := ImplicitAuthenticationParameters{}
	this.AuthenticationType = authenticationType
	return &this
}

// NewImplicitAuthenticationParametersWithDefaults instantiates a new ImplicitAuthenticationParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImplicitAuthenticationParametersWithDefaults() *ImplicitAuthenticationParameters {
	this := ImplicitAuthenticationParameters{}
	return &this
}

func (o ImplicitAuthenticationParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImplicitAuthenticationParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ImplicitAuthenticationParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authenticationType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImplicitAuthenticationParameters := _ImplicitAuthenticationParameters{}

	err = json.Unmarshal(data, &varImplicitAuthenticationParameters)

	if err != nil {
		return err
	}

	*o = ImplicitAuthenticationParameters(varImplicitAuthenticationParameters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableImplicitAuthenticationParameters struct {
	value *ImplicitAuthenticationParameters
	isSet bool
}

func (v NullableImplicitAuthenticationParameters) Get() *ImplicitAuthenticationParameters {
	return v.value
}

func (v *NullableImplicitAuthenticationParameters) Set(val *ImplicitAuthenticationParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableImplicitAuthenticationParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableImplicitAuthenticationParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImplicitAuthenticationParameters(val *ImplicitAuthenticationParameters) *NullableImplicitAuthenticationParameters {
	return &NullableImplicitAuthenticationParameters{value: val, isSet: true}
}

func (v NullableImplicitAuthenticationParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImplicitAuthenticationParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


