/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the FileStorageConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileStorageConfigInfo{}

// FileStorageConfigInfo file storage configuration info
type FileStorageConfigInfo struct {
	StorageConfigInfo
	AdditionalProperties map[string]interface{}
}

type _FileStorageConfigInfo FileStorageConfigInfo

// NewFileStorageConfigInfo instantiates a new FileStorageConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileStorageConfigInfo(storageType string) *FileStorageConfigInfo {
	this := FileStorageConfigInfo{}
	this.StorageType = storageType
	return &this
}

// NewFileStorageConfigInfoWithDefaults instantiates a new FileStorageConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileStorageConfigInfoWithDefaults() *FileStorageConfigInfo {
	this := FileStorageConfigInfo{}
	return &this
}

func (o FileStorageConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileStorageConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FileStorageConfigInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"storageType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileStorageConfigInfo := _FileStorageConfigInfo{}

	err = json.Unmarshal(data, &varFileStorageConfigInfo)

	if err != nil {
		return err
	}

	*o = FileStorageConfigInfo(varFileStorageConfigInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFileStorageConfigInfo struct {
	value *FileStorageConfigInfo
	isSet bool
}

func (v NullableFileStorageConfigInfo) Get() *FileStorageConfigInfo {
	return v.value
}

func (v *NullableFileStorageConfigInfo) Set(val *FileStorageConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFileStorageConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFileStorageConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileStorageConfigInfo(val *FileStorageConfigInfo) *NullableFileStorageConfigInfo {
	return &NullableFileStorageConfigInfo{value: val, isSet: true}
}

func (v NullableFileStorageConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileStorageConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
