/*
Polaris Management Service

Defines the management APIs for using Polaris to create and manage Iceberg catalogs and their principals

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polarismgmt

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateCatalogRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCatalogRequest{}

// CreateCatalogRequest Request to create a new catalog
type CreateCatalogRequest struct {
	Catalog              Catalog `json:"catalog"`
	AdditionalProperties map[string]interface{}
}

type _CreateCatalogRequest CreateCatalogRequest

// NewCreateCatalogRequest instantiates a new CreateCatalogRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCatalogRequest(catalog Catalog) *CreateCatalogRequest {
	this := CreateCatalogRequest{}
	this.Catalog = catalog
	return &this
}

// NewCreateCatalogRequestWithDefaults instantiates a new CreateCatalogRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCatalogRequestWithDefaults() *CreateCatalogRequest {
	this := CreateCatalogRequest{}
	return &this
}

// GetCatalog returns the Catalog field value
func (o *CreateCatalogRequest) GetCatalog() Catalog {
	if o == nil {
		var ret Catalog
		return ret
	}

	return o.Catalog
}

// GetCatalogOk returns a tuple with the Catalog field value
// and a boolean to check if the value has been set.
func (o *CreateCatalogRequest) GetCatalogOk() (*Catalog, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Catalog, true
}

// SetCatalog sets field value
func (o *CreateCatalogRequest) SetCatalog(v Catalog) {
	o.Catalog = v
}

func (o CreateCatalogRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCatalogRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["catalog"] = o.Catalog

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateCatalogRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"catalog",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCatalogRequest := _CreateCatalogRequest{}

	err = json.Unmarshal(data, &varCreateCatalogRequest)

	if err != nil {
		return err
	}

	*o = CreateCatalogRequest(varCreateCatalogRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "catalog")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateCatalogRequest struct {
	value *CreateCatalogRequest
	isSet bool
}

func (v NullableCreateCatalogRequest) Get() *CreateCatalogRequest {
	return v.value
}

func (v *NullableCreateCatalogRequest) Set(val *CreateCatalogRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCatalogRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCatalogRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCatalogRequest(val *CreateCatalogRequest) *NullableCreateCatalogRequest {
	return &NullableCreateCatalogRequest{value: val, isSet: true}
}

func (v NullableCreateCatalogRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCatalogRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
